;; **************   All-shaq-qvars-scales-list.lisp ****************
;; NUM-QVARS = 713; NUM-SCALES 65; NUM-SUBSCALES 59 (each start with 0)
;;; TOTAL-VARS = 713 + 65 + 59 = 837
;;  ALSO LISTS QVAR-LABEL PAIRS IN SPSS FORMAT AFTER QVARS AND SCALES
;;
0 "CaseNum"
1 "CaseType"
2 "SourceFile"
3 "FileDate"
4 "Instr"
5 "Resr"
6 "Name"
7 "UserID"
8 "Sex"
9 "Age"
10 "Email"
11 "ZipCode"
12 "Nation"
13 "HrsWork"
14 "utype"
15 "twanttho"
16 "tknowmor"
17 "twanthel"
18 "twantspe"
19 "texperie"
20 "tprevshaq"
21 "wantspq"
22 "tu100stu"
23 "tcsulbst"
24 "tcolstu"
25 "totherst"
26 "tressub"
27 "tcolfaca"
28 "u-none"
29 "ugoals"
30 "gsuchap"
31 "gemocop"
32 "gslfest"
33 "gprocrst"
34 "gtimeman"
35 "grelat"
36 "gmeetpeo"
37 "glonelyf"
38 "gexvalus"
39 "gdepres"
40 "ganxfear"
41 "gaggrang"
42 "gacadsuc"
43 "gcomplta1"
44 "gcompltanomaj"
45 "gcompltanoac"
46 "gcarplan"
47 "gcaronly"
48 "gnottake"
49 "scalessel"
50 "xhqonly"
51 "xhq-acad"
52 "xhq-acad-car"
53 "xvalues-th"
54 "xworldview"
55 "xsel-f-bels"
56 "xiecontrol"
57 "xselfconf"
58 "xselfman"
59 "xemotcop"
60 "xinterpers"
61 "xacadlearn"
62 "xcarint"
63 "xsehappy"
64 "xsrdepres"
65 "xsranxiet"
66 "xsrangagg"
67 "sFamily"
68 "OlderBrosN"
69 "OlderSisN"
70 "YoungerBrosN"
71 "YoungerSisN"
72 "Raised2Parents"
73 "SingleFparent"
74 "SingleMparent"
75 "RaisedNoParents"
76 "RaisedOther"
77 "bio3educ"
78 "biohsgpa"
79 "biocolle"
80 "bio4job"
81 "student"
82 "manager"
83 "propeop"
84 "protech"
85 "consulta"
86 "educator"
87 "sales"
88 "technici"
89 "clerical"
90 "service"
91 "ownbus10"
92 "othrsfem"
93 "other"
94 "bio7lang"
95 "lenglish"
96 "lspanish"
97 "lvietnam"
98 "lcambodn"
99 "lchinese"
100 "lkorean"
101 "lportugu"
102 "lgerman"
103 "lfrench"
104 "lothrasn"
105 "lothreur"
106 "lother"
107 "bio1ethn"
108 "enortham"
109 "eafrica"
110 "enoreur"
111 "esoueur"
112 "ecambodn"
113 "echina"
114 "ekorea"
115 "ejapan"
116 "evietnam"
117 "eothrasn"
118 "emexico"
119 "ecentram"
120 "esoutham"
121 "epacific"
122 "eother"
123 "biorelaf"
124 "catholic"
125 "jewish"
126 "latterd"
127 "buddhist"
128 "baptist"
129 "methodst"
130 "episcop"
131 "lutheran"
132 "presbyte"
133 "proliber"
134 "profunda"
135 "noaffil"
136 "agnostic"
137 "othrnoan"
138 "family"
139 "OlderBrN"
140 "OlderSisN"
141 "YoungBrN"
142 "YoungSisN"
143 "Raised2Parents"
144 "SingleMparent"
145 "SingleFparent"
146 "RaisedNoParents"
147 "RaisedOther"
148 "stucolle"
149 "cocsulb"
150 "cccsu"
151 "coucal"
152 "coopublc"
153 "coprivca"
154 "coprivot"
155 "cocacomc"
156 "coothcc"
157 "coothnat"
158 "coprgrad"
159 "cotech"
160 "highsch"
161 "coother"
162 "stumajor"
163 "mlibart"
164 "msocsci"
165 "mbiolsci"
166 "mart"
167 "mnatsci"
168 "mbus"
169 "menginr"
170 "meducat"
171 "mmedical"
172 "motcompu"
173 "mothtech"
174 "mrecrpe"
175 "mdoesna"
176 "mundecid"
177 "stuspeci"
178 "strancc"
179 "stran4yr"
180 "sadultre"
181 "seop"
182 "susimmig"
183 "svisa"
184 "shonor"
185 "svisastu"
186 "sdisabld"
187 "soutofst"
188 "smilitar"
189 "sathlete"
190 "snone"
191 "sturesid"
192 "rsinwpar"
193 "rsindorm"
194 "rsinwchl"
195 "rsinothr"
196 "rmarwoch"
197 "rmarwchl"
198 "rmarlike"
199 "rother"
200 "stpared"
201 "stuclass"
202 "studegre"
203 "stusemes"
204 "stmajgpa"
205 "stacadst"
206 "stgpatre"
207 "trconhi"
208 "trincryr"
209 "trincyru"
210 "trincyrs"
211 "trgradin"
212 "trconave"
213 "trdecyru"
214 "trdecyr"
215 "trconlow"
216 "trupandd"
217 "trother"
218 "stuverba"
219 "stumatha"
220 "stulookf"
221 "stulikei"
222 "stucomfo"
223 "stufrien"
224 "stuextmo"
225 "stuenjoy"
226 "stucaree"
227 "stumoney"
228 "stuconfu"
229 "stufinde"
230 "stueactr"
231 "sthapcol"
232 "sthapgpa"
233 "sturesource"
234 "afinanc"
235 "afampres"
236 "afamresp"
237 "aworktim"
238 "awrkpres"
239 "arelprob"
240 "aloneli"
241 "ahomstpl"
242 "aschstpl"
243 "acompavl"
244 "awrngcls"
245 "afacconn"
246 "astuconn"
247 "alowmotv"
248 "atimconf"
249 "aprocras"
250 "acmstudy"
251 "acmndrop"
252 "acmatten"
253 "acmefaml"
254 "acmesocs"
255 "acmconce"
256 "acmtime"
257 "acmtimeORIG"
258 "acmselfs"
259 "acmcompl"
260 "acmquitc"
261 "acmfinan"
262 "acmdegre"
263 "lrnestud"
264 "lrntxove"
265 "lrntxund"
266 "lrntsrev"
267 "lrnmap"
268 "lrntextn"
269 "lrninter"
270 "lrnrote"
271 "lrnassoc"
272 "lrnstrug"
273 "lrntheor"
274 "lrnalone"
275 "lrnmath"
276 "lrnwrpap"
277 "lrntxout"
278 "lrnnotes"
279 "lrnwrskl"
280 "lrnsee"
281 "lrnvocab"
282 "lrnsread"
283 "lrnmemor"
284 "lrntense"
285 "lrnsefic"
286 "lrnwrorg"
287 "lrnunasn"
288 "lrncolmt"
289 "lrnknowt"
290 "lrnproof"
291 "lrnrread"
292 "lrneffic"
293 "lrntestt"
294 "lrntimas"
295 "lrntired"
296 "lrntanxi"
297 "lrnsmart"
298 "lrnaread"
299 "lrnrslow"
300 "smtbusy"
301 "smtfutur"
302 "smtexerc"
303 "smteath"
304 "smtsleep"
305 "smtsdeve"
306 "smtnproc"
307 "smtptodo"
308 "smtgoals"
309 "smtschd"
310 "smt2dtod"
311 "smtacmpl"
312 "smtghelp"
313 "smtbalan"
314 "smthabch"
315 "copnegth"
316 "copcopea"
317 "coppsolv"
318 "copemota"
319 "copavops"
320 "copblame"
321 "copwdrw"
322 "copfun"
323 "coptalks"
324 "coppepta"
325 "copsmoke"
326 "copdrug"
327 "coppe"
328 "copnegph"
329 "copselfb"
330 "copposph"
331 "copexpec"
332 "cophappy"
333 "copavoat"
334 "copselfe"
335 "thm1ach"
336 "thm3educ"
337 "thm4mone"
338 "thm25pos"
339 "thm26suc"
340 "thmimpac"
341 "thm28cre"
342 "thm30ceo"
343 "thm33goa"
344 "thm8roma"
345 "thm12ple"
346 "thmrespe"
347 "thm20int"
348 "thmliked"
349 "thmcareg"
350 "thmsuppo"
351 "thmatten"
352 "thmfamil"
353 "thmrecog"
354 "thmphurt"
355 "thmobgod"
356 "thmparlv"
357 "thmsprot"
358 "thmpunct"
359 "thmoblig"
360 "thm5adve"
361 "thm6lear"
362 "thm9shap"
363 "thm10oth"
364 "thmrelgd"
365 "thm14ind"
366 "thm22bod"
367 "thm23bal"
368 "thmorder"
369 "thmmench"
370 "thm34exp"
371 "thmcompc"
372 "thminteg"
373 "thmphil"
374 "thmclean"
375 "thmwhole"
376 "thmperfe"
377 "thmjusti"
378 "thmsimpl"
379 "thmbeaut"
380 "thmgoodn"
381 "thmuniqu"
382 "thmcreat"
383 "thmefort"
384 "thmplayf"
385 "thmsesuf"
386 "thmsedis"
387 "thmspiri"
388 "thmrelig"
389 "thmuncon"
390 "tbvothfi"
391 "tbvliked"
392 "tbvweak"
393 "tbvbest"
394 "tbventit"
395 "tbvrules"
396 "tbvwinne"
397 "tbvbalan"
398 "tbvhapca"
399 "tbvgrati"
400 "thvselfa"
401 "thvselfaORIG"
402 "thvuncon"
403 "thvselfw"
404 "iecselfs"
405 "iecicont"
406 "iecgenet"
407 "iecpeopl"
408 "iecdepen"
409 "ieccofee"
410 "ieccoprb"
411 "wovprogr"
412 "wovgoodf"
413 "wovmylif"
414 "wovnfair"
415 "woventit"
416 "wovinjur"
417 "wovabund"
418 "wovgrate"
419 "wovposth"
420 "wovhappy"
421 "wovpoor"
422 "wovill"
423 "wovdeath"
424 "wovalone"
425 "wovnolov"
426 "wovliked"
427 "wovperso"
428 "wovprobl"
429 "wovdisco"
430 "wovsucce"
431 "wovoverc"
432 "slflearn"
433 "slfcritt"
434 "slfresea"
435 "slfanaly"
436 "slfsynth"
437 "slfcreat"
438 "slfcompu"
439 "slfbiosc"
440 "slfnatsc"
441 "slflibar"
442 "slfsocsc"
443 "slfphilr"
444 "slfperfa"
445 "slffinea"
446 "slfbusan"
447 "slfheal2"
448 "slfengin"
449 "slfeduch"
450 "slfiq"
451 "slfdecma"
452 "slftimem"
453 "slfcope"
454 "slfself4"
455 "slfselfm"
456 "slfachan"
457 "slfmana6"
458 "slfheal3"
459 "slfmeetp"
460 "slfliste"
461 "slfself5"
462 "slfconfl"
463 "slfpersu"
464 "slfmana7"
465 "slfhelps"
466 "slfspeak"
467 "slfjobse"
468 "slfadapt"
469 "slfhappy"
470 "slfoptim"
471 "slffrien"
472 "slfindep"
473 "cr1issue"
474 "crresolv"
475 "crnthrea"
476 "crunderl"
477 "crtklong"
478 "crnneglb"
479 "crteweak"
480 "crwinwin"
481 "crlongtk"
482 "crexaggr"
483 "crmanipu"
484 "crsummar"
485 "crcprais"
486 "crboassr"
487 "crophone"
488 "crreprai"
489 "crteach"
490 "crifavor"
491 "crifolup"
492 "crangang"
493 "criprais"
494 "crangres"
495 "crtlkmor"
496 "creqwin"
497 "instshlp"
498 "intcomit"
499 "intundrl"
500 "inttelal"
501 "intsmgoa"
502 "inteqdec"
503 "intiopen"
504 "intweopn"
505 "intdaily"
506 "intrespt"
507 "intallop"
508 "intwktog"
509 "intknpfe"
510 "intlsqpr"
511 "intlove"
512 "inrbealnORIG"
513 "inrbealn"
514 "inalcnstORIG"
515 "inalcnst"
516 "inrfrien"
517 "indifdec"
518 "inrlunch"
519 "inrinhap"
520 "innevarg"
521 "inrigrow"
522 "inrsaywe"
523 "incomtwo"
524 "indifgoa"
525 "infindan"
526 "inenalon"
527 "inokalon"
528 "inrhatea"
529 "inrfreeh"
530 "insepint"
531 "inrmoney"
532 "romsurpr"
533 "romfanta"
534 "romceleb"
535 "romplace"
536 "romattra"
537 "romplayf"
538 "romcharm"
539 "lromtask"
540 "lroftask"
541 "lrmfinal"
542 "lroembar"
543 "lromstro"
544 "lroeqinc"
545 "lrcarcon"
546 "haparea"
547 "hapclfrn"
548 "hapcarnw"
549 "hapcarfu"
550 "hapfrien"
551 "hapwkrel"
552 "happe"
553 "haprecre"
554 "hapsexre"
555 "hapfamil"
556 "hapselfd"
557 "hapspiri"
558 "hapyear"
559 "hap3year"
560 "haplife"
561 "hapexpec"
562 "rhlfreqi"
563 "rhlalcoh"
564 "rhlsmoke"
565 "rhldrugs"
566 "rhlphysi"
567 "rhlWeigh"
568 "rpehapfr"
569 "rpehmarr"
570 "rpenetw"
571 "rpeclfrn"
572 "rpenumfr"
573 "rpenumcl"
574 "rpecommi"
575 "rdepfeel"
576 "rdepthou"
577 "rdepdyss"
578 "rdepmajs"
579 "rdepmeds"
580 "rdepther"
581 "ranxperf"
582 "ranxallt"
583 "ranxpstd"
584 "ranxsoci"
585 "ranxocd"
586 "ranxphob"
587 "ranxpani"
588 "ranxmeds"
589 "ranxther"
590 "rangfeel"
591 "rangyell"
592 "rangdomi"
593 "rangthou"
594 "rangdest"
595 "tb2relat"
596 "tb2punis"
597 "tbv2notr"
598 "tb2groum"
599 "tb2selfm"
600 "tb2gdwrk"
601 "tb2gdatt"
602 "tb2allgd"
603 "tb2reaso"
604 "tbv2astr"
605 "tb2idhum"
606 "tb2lifad"
607 "tb2movem"
608 "tbv2core"
609 "car1carg"
610 "car1carp"
611 "car1inat"
612 "caribioh"
613 "carisocs"
614 "carihelp"
615 "carimath"
616 "carimed"
617 "cariwrit"
618 "carifnar"
619 "cariethn"
620 "carilear"
621 "cariexpe"
622 "carigene"
623 "carinoin"
624 "carilit"
625 "carirecp"
626 "caripoli"
627 "carimil6"
628 "carimanu"
629 "carilang"
630 "cariphil"
631 "caribusi"
632 "cariengi"
633 "carifamc"
634 "cariwoma"
635 "caricom8"
636 "carinte0"
637 "caribmar"
638 "caribman"
639 "caribinf"
640 "caribfin"
641 "caribhrd"
642 "caribacc"
643 "carispbu"
644 "carieeng"
645 "carime"
646 "cariche2"
647 "caricive"
648 "cariaero"
649 "carieite"
650 "caricom9"
651 "caribcom"
652 "carimusi"
653 "cariart"
654 "caridram"
655 "caridanc"
656 "cariphot"
657 "carindde"
658 "carinte1"
659 "cariteac"
660 "caricoun"
661 "carieduc"
662 "carihadu"
663 "carihchi"
664 "caritvoc"
665 "caricom4"
666 "carsocwo"
667 "cark12te"
668 "carminis"
669 "carifren"
670 "cariital"
671 "carigerm"
672 "cariruss"
673 "carijapn"
674 "carichin"
675 "cariclas"
676 "carispan"
677 "caripor"
678 "carimd"
679 "carinurs"
680 "caripthe"
681 "cariheal"
682 "carikine"
683 "caricom5"
684 "carmedte"
685 "carilaw"
686 "caricrim"
687 "carimil7"
688 "cariche3"
689 "cariphys"
690 "carigeol"
691 "cariastr"
692 "carienvi"
693 "caripsyc"
694 "carisoco"
695 "carihist"
696 "caripols"
697 "cariecon"
698 "cargeogr"
699 "cariamer"
700 "cariantr"
701 "carianth"
702 "carispee"
703 "carling"
704 "cariaist"
705 "caribstu"
706 "carimexa"
707 "cariasam"
708 "cariamst"
709 "cariwstu"
710 "cariengl"
711 "carijour"
712 "UserRate"

;;xxx  ***************** all-shaq-scales-list ****************
0 "ST1HIGHERSELF"
1 "ST2SOCINTIMNOFAM"
2 "ST3FAMCARE"
3 "ST4SUCCESSSTATUSMATER"
4 "ST5-ORDERPERFECTIONGOODNESS"
5 "ST6GODSPIRITRELIG"
6 "ST7IMPACTCHALLENGEEXPLOR"
7 "ST8ATTENTIONFUNEASY"
8 "ST9VALUESELFALLUNCOND"
9 "ST10OVERCMPROBACCEPTSELF"
10 "ST11DUTYPUNCTUAL"
11 "SWORLDVIEW"
12 "STBSLFWO"
13 "SIECONTR"
14 "SETHBEL"
15 "SGRFEARS"
16 "SSLFCONF"
17 "SSELFMAN"
18 "SEMOTCOP"
19 "INTSS1AASSERTCR"
20 "INTSS1BOPENHON"
21 "INTSS2ROMANTC"
22 "INTSS3LIBROLE"
23 "INTSS4LOVERES"
24 "INTSS5INDEP"
25 "INTSS6POSSUP"
26 "INTSS7COLLAB"
27 "SCOLLEGE"
28 "SSL1CONFIDEFFICSTUDYTEST"
29 "SSL1BCONFIDNOTAVOIDSTUDY"
30 "SSL2SATISCAMPUSFACFRIENDSGRDES"
31 "SSL3WRITINGSKILLS"
32 "SSL4BLDMENTALSTRUCT"
33 "SSL5BASICSTUDYSKILLS"
34 "SSL6SELFMANACADGOALS"
35 "SSL7MATHSCIPRINC"
36 "SSL8STUDYENVIR"
37 "SSL9ATTENDHW"
38 "SSL10MEMNOTANX"
39 "SSL11NOTNONACADMOT"
40 "SSL12STDYTMAVAIL"
41 "SSL13VERBALAPT"
42 "SSL14MATHAPT"
43 "SINCAR"
44 "SINBUS"
45 "SINENGR"
46 "SINFINEA"
47 "SINHELP"
48 "SINLANG"
49 "SINMED"
50 "SINMILTC"
51 "INNATSCI"
52 "SINSOCSC"
53 "SINWOETH"
54 "SINWRITE"
55 "SEHAPPY"
56 "SRDEPRES"
57 "SRANXIET"
58 "SRANGAGG"
59 "SRELHLTH"
60 "SRPEOPLE"
61 "SUSERFEEDBACK"

;; xxx ************************** ALL SHAQ SUBSCALES ****************
;;
0 "SSWVGRATPT"
1 "SSWVOPTIMS"
2 "SSWVENTIT"
3 "SSSWNONCONT"
4 "SSSWHAPALLGRAT"
5 "SSSWACALLSELF"
6 "SSIEAUTONY"
7 "SSIENCODEP"
8 "SSIENOTHER"
9 "SSB2ETHIC"
10 "SSB2FORGIV"
11 "SSB2IDGRND"
12 "SSB2GRNDMNG"
13 "SSB2INRGOOD"
14 "SSB2NOASTR"
15 "SSB2LIFAD"
16 "SSWFSOCIAL"
17 "SSWFSELF"
18 "SSWFPOVFAI"
19 "SSWFILLDEA"
20 "SSSCLEARN"
21 "SSSCCOPOPT"
22 "SSSCSMSMSD"
23 "SSSCINTERP"
24 "SSSCALLHELP"
25 "SSSCSCIENCE"
26 "SSSCARTCRE"
27 "SSSMTIMEMANGOALSET"
28 "SSSMACCOMPLORUSH"
29 "SSSMSELFDEVEL"
30 "SSSMHEALTHHABS"
31 "SSCPPROBSOLV"
32 "SSCPPOSTHOUGHTS"
33 "SSCPPOSACTS"
34 "SSCPNOBLAMEANGERWDRAW"
35 "SSCPNOTSMOKDRUGMED"
36 "SSCPNOTEAT"
37 "HAPSDMEANSPIRITSS"
38 "HAPCAREEREXSS"
39 "HAPRECPESS"
40 "HAPAREASS"
41 "HAPFAMSS"
42 "HAPROMSS"
43 "HAPFRIENDSSS"
44 "HAPFUTURESS"
45 "HAPPASTSS"
46 "HAPRECENTSS"
47 "SSRECLOSEFRIENDS"
48 "SSREROMRELSUC"
49 "SSRENUMFRIENDS"
50 "SSREHAPSUCFRS"
51 "SSDELODEPSYMP"
52 "SSDELODEPTREATS"
53 "SSAXLOPERFGENANX"
54 "SSAXLOWFEAROCD"
55 "SSAXLOANXTREATS"
56 "SSHELONEGADDICTHABS"
57 "SSHELOFREQILL"
58 "SSHEPELOWEIGHT"


;; XXX ****************************** QVAR-LABEL LIST ****************
;;
("CaseNum  'CaseNumOrigFile'"
 "CaseType  ''"
 "SourceFile  'Source files PARTnum'"
 "FileDate  'File Date'"
 "Instr  'Instructor'"
 "Resr  'Researcher'"
 "Name  'Name'"
 "UserID  'UserID'"
 "Sex  'Sex 1=M 2=F'"
 "Age  'Age'"
 "Email  'Email'"
 "ZipCode  'ZipCode'"
 "Nation  'Nation'"
 "HrsWork  'HrsWork'"
 "utype  'UserType'"
 "twanttho  't-Want thorough assessment'"
 "tknowmor  't-Want to know of self'"
 "twanthel  't-Want help with problem'"
 "twantspe  't-Want specific help'"
 "texperie  't-Experienced self-help user'"
 "tprevshaq  't-Previous SHAQ user'"
 "wantspq  'g-Specific questionnaire'"
 "tu100stu  't-CSULB U100 student'"
 "tcsulbst  't-CSULB other student'"
 "tcolstu  't-Other college student'"
 "totherst  't-Other student'"
 "tressub  't-SHAQ research subject'"
 "tcolfaca  't-College faculty-admin'"
 "u-none  't-none of above'"
 "ugoals  'UserGoals'"
 "gsuchap  'g-Success-happiness'"
 "gemocop  'g-Emotional coping'"
 "gslfest  'g-Self-esteem'"
 "gprocrst  'g-Procrastination'"
 "gtimeman  'g-Time Management'"
 "grelat  'g-Relationships'"
 "gmeetpeo  'g-Meeting people'"
 "glonelyf  'g-Loneliness'"
 "gexvalus  'g-Explore Values'"
 "gdepres  'g-Depression'"
 "ganxfear  'g-Anxiety-fears'"
 "gaggrang  'g-Aggression-anger'"
 "gacadsuc  'g-Academic success'"
 "gcomplta1  'g-Complete assessent'"
 "gcompltanomaj  'g-Complete assess-no major'"
 "gcompltanoac  'g-Complete assessment-no acad'"
 "gcarplan  'g-Career planning'"
 "gcaronly  'g-Career help only'"
 "gnottake  'g-Not taking for self'"
 "scalessel  'Direct-scales-selected'"
 "xhqonly  'sel-HQonly'"
 "xhq-acad  'sel-HQ-ACAD'"
 "xhq-acad-car  'sel-HQ-ACAD'"
 "xvalues-th  'sel-ValuesThemes'"
 "xworldview  'sel-Worldview'"
 "xsel-f-bels  'sel-SelfLifeBel'"
 "xiecontrol  'sel-IEcontrol'"
 "xselfconf  'sel-SelfConfidence'"
 "xselfman  'sel-SelfManagmt'"
 "xemotcop  'sel-emotcope'"
 "xinterpers  'sel-interpers'"
 "xacadlearn  'sel-Acad-Learn'"
 "xcarint  'sel-career-int'"
 "xsehappy  'sel-outc-happy'"
 "xsrdepres  'sel-outc-depres'"
 "xsranxiet  'sel-outc-anxiety'"
 "xsrangagg  'sel-outc-anger-aggr'"
 "sFamily  'SibPosit-Parnts'"
 "OlderBrosN  'NumOlderBros'"
 "OlderSisN  'NumOlderSis'"
 "YoungerBrosN  'NumYoungerBros'"
 "YoungerSisN  'NumYoungerSis'"
 "Raised2Parents  'Raised2Parents'"
 "SingleFparent  'SingleFparent'"
 "SingleMparent  'SingleMparent'"
 "RaisedNoParents  'RaisedNoParents'"
 "RaisedOther  'RaisedOther'"
 "bio3educ  'b-Highest education completed'"
 "biohsgpa  'b-High school GPA'"
 "biocolle  'b-College GPA'"
 "bio4job  'b-Primary occupation'"
 "student  '1-Student'"
 "manager  '2-Manager'"
 "propeop  '3-People professional'"
 "protech  '4-Technical professional'"
 "consulta  '5-Consultant'"
 "educator  '6-Educator'"
 "sales  '7-Sales'"
 "technici  '8-Other technical'"
 "clerical  '9-Clerical'"
 "service  '10-Service'"
 "ownbus10  '11-Own business'"
 "othrsfem  '12-other occupation'"
 "other  '13-Other'"
 "bio7lang  'b-Fluent languages'"
 "lenglish  'lenglish'"
 "lspanish  'lspanish'"
 "lvietnam  'lvietnam'"
 "lcambodn  'lcambodn'"
 "lchinese  'lchinese'"
 "lkorean  'lkorean'"
 "lportugu  'lportugu'"
 "lgerman  'lgerman'"
 "lfrench  'lfrench'"
 "lothrasn  'lothrasn'"
 "lothreur  'lothreur'"
 "lother  'lother'"
 "bio1ethn  'Primary Ethnic Group'"
 "enortham  'enortham'"
 "eafrica  'eafrica'"
 "enoreur  'enoreur'"
 "esoueur  'esoueur'"
 "ecambodn  'ecambodn'"
 "echina  'echina'"
 "ekorea  'ekorea'"
 "ejapan  'ejapan'"
 "evietnam  'evietnam'"
 "eothrasn  'eothrasn'"
 "emexico  'emexico'"
 "ecentram  'ecentram'"
 "esoutham  'esoutham'"
 "epacific  'epacific'"
 "eother  'eother'"
 "biorelaf  'bioRelAffiliation'"
 "catholic  'Catholic'"
 "jewish  'Jewish'"
 "latterd  'Latter Day Saints'"
 "buddhist  'Buddhist'"
 "baptist  'Baptist'"
 "methodst  'United Methodist'"
 "episcop  'Episopalian'"
 "lutheran  'Lutheran'"
 "presbyte  'Presbyterian'"
 "proliber  'Other liberal'"
 "profunda  'Other fundamentalist'"
 "noaffil  'No affiliation'"
 "agnostic  'Agnostic'"
 "othrnoan  'Other'"
 "family  'famConstellation'"
 "OlderBrN  'NumOlderBros'"
 "OlderSisN  'NumOlderSis'"
 "YoungBrN  'NumYoungrBros'"
 "YoungSisN  'NumYoungrSis'"
 "Raised2Parents  'Raised by 2 Parents'"
 "SingleMparent  'RaisedBySingleMale'"
 "SingleFparent  'RaisedBySingleFemale'"
 "RaisedNoParents  'RaisedByNoParents'"
 "RaisedOther  'RaisedOther'"
 "stucolle  'st-College attending'"
 "cocsulb  'CSULB'"
 "cccsu  'CSU Campus'"
 "coucal  'UC Campus'"
 "coopublc  'Other Public U'"
 "coprivca  'CA Private U'"
 "coprivot  'Other Private U'"
 "cocacomc  'CA Com Col'"
 "coothcc  'Other Com Col'"
 "coothnat  'Other Nation Col'"
 "coprgrad  'NonAff Grad Sch'"
 "cotech  'Tech Col'"
 "highsch  'HS'"
 "coother  'Other'"
 "stumajor  'st-Major study area'"
 "mlibart  'Lib Art major'"
 "msocsci  'Soc Sci major'"
 "mbiolsci  'Bio Sci major'"
 "mart  'Art major'"
 "mnatsci  'Nat Sci major'"
 "mbus  'Bus major'"
 "menginr  'Engr major'"
 "meducat  'Educ major'"
 "mmedical  'Medical major'"
 "motcompu  'Computer major'"
 "mothtech  'Other tech majo'"
 "mrecrpe  'Recr-PE major'"
 "mdoesna  'Does not apply'"
 "mundecid  'Undecided'"
 "stuspeci  'st-Special status'"
 "strancc  'Com college transfer'"
 "stran4yr  '4yr college transfer'"
 "sadultre  'Returning adult'"
 "seop  'EOP'"
 "susimmig  'Immigrant'"
 "svisa  'Visa student'"
 "shonor  'Honors program'"
 "svisastu  'Visa student'"
 "sdisabld  'Disabled student'"
 "soutofst  'Out-of-state student'"
 "smilitar  'Military-active or vet'"
 "sathlete  'Student athlete'"
 "snone  'None of above'"
 "sturesid  'st-Residence'"
 "rsinwpar  'Live with parents'"
 "rsindorm  'Live in dorms'"
 "rsinwchl  'Single with children'"
 "rsinothr  'Single other'"
 "rmarwoch  'Married without children'"
 "rmarwchl  'Married with children'"
 "rmarlike  'Marital like situation'"
 "rother  'Other'"
 "stpared  'b-Highest parents educ level'"
 "stuclass  'st-Class level'"
 "studegre  'st-Educ objective level'"
 "stusemes  'st-Units this semester'"
 "stmajgpa  'st-Major GPA'"
 "stacadst  'st-AcadStatus'"
 "stgpatre  'st-GPA Trends'"
 "trconhi  'Consistently high'"
 "trincryr  'Increased after absence'"
 "trincyru  'Increased past year or so'"
 "trincyrs  'Increased a few sems ago'"
 "trgradin  'Gradually increased'"
 "trconave  'Consistently average'"
 "trdecyru  'Decreased a few sems ago'"
 "trdecyr  'Decreased past year or so'"
 "trconlow  'Consistently low'"
 "trupandd  'Up and down dramatically'"
 "trother  'Other'"
 "stuverba  'st-Verbal aptitude scores'"
 "stumatha  'st-Math aptitude scores'"
 "stulookf  'sa-Look forward to campus'"
 "stulikei  'sa-Like instructors-can talk'"
 "stucomfo  'sa-Comfortable w/ area fac & students'"
 "stufrien  'sa-Current school friends'"
 "stuextmo  'sa-NotParents expectations main motive'"
 "stuenjoy  'sa-Enjoy learning, classes, homework'"
 "stucaree  'sa-Career-job main motive'"
 "stumoney  'sa-NotMoney main motive'"
 "stuconfu  'sa-NotConfused why I am in college'"
 "stufinde  'sa-Financial support'"
 "stueactr  'sa-Enjoying life and fun in school'"
 "sthapcol  'sa-Overall college exper happiness'"
 "sthapgpa  'sa-Happiness with grades'"
 "sturesource  'am-All interference factors'"
 "afinanc  '1-Financial worries'"
 "afampres  '2-Family pressures'"
 "afamresp  '3-Family responsibilities'"
 "aworktim  '4-Job time'"
 "awrkpres  '5-Work pressures'"
 "arelprob  '6-Relationship problems'"
 "aloneli  '7-Loneliness'"
 "ahomstpl  '8-No home study place'"
 "aschstpl  '9-No school study place'"
 "acompavl  '10-Computer availability'"
 "awrngcls  '11-Wrong classes'"
 "afacconn  '12-Poor faculty connection'"
 "astuconn  '13-Poor student connection'"
 "alowmotv  '14-Low study motivation'"
 "atimconf  '15-Too many task conflicts'"
 "aprocras  '16-Procrastination'"
 "acmstudy  'am-Study time per class hour'"
 "acmndrop  'am-Never drop or take incomplete'"
 "acmatten  'am-Attendance & do homework'"
 "acmefaml  'am-HW encouraged by fam & friends'"
 "acmesocs  'am-No chores if conflict w HW'"
 "acmconce  'am-Great task-HW concentration'"
 "acmtime  'am-Time available to study'"
 "acmtimeORIG  'am-Time available to study--should be reversed'"
 "acmselfs  'am-Self-manage college life well'"
 "acmcompl  'am-Confident will complete degree'"
 "acmquitc  'am-Won't drop out in year'"
 "acmfinan  'am-Confidence school finances'"
 "acmdegre  'am-Motivation for degree'"
 "lrnestud  'lh-Good study place w/o distract'"
 "lrntxove  'lh-Prevew, points, review chapters'"
 "lrntxund  'lh-Stop to understand readings'"
 "lrntsrev  'lh-Review 3 times before exam'"
 "lrnmap  'lh-Create visual map of readings'"
 "lrntextn  'lh-Math science seek basic principles'"
 "lrninter  'lh-If text boring, make interesting'"
 "lrnrote  'lh-New view--not rote methods'"
 "lrnassoc  'lh-Try to create associations'"
 "lrnstrug  'lh-Struggle with difficult material'"
 "lrntheor  'lh-Build own theories'"
 "lrnalone  'lh-Study alone-minimal help'"
 "lrnmath  'la-Enjoy & good at math'"
 "lrnwrpap  'la-A's on term papers'"
 "lrntxout  'la-Outline textbooks'"
 "lrnnotes  'la-Good class notes'"
 "lrnwrskl  'la-Satisfied with writing skills'"
 "lrnsee  'la-No vision problems'"
 "lrnvocab  'la-No vocabulary problems reading'"
 "lrnsread  'la-Not read slower'"
 "lrnmemor  'la-Memory for terms,formulas,facts'"
 "lrntense  'la-Rarely tense in exams'"
 "lrnsefic  'la-Learning time efficient'"
 "lrnwrorg  'la-Organizing writing good'"
 "lrnunasn  'ld-Understand & begin assignments'"
 "lrncolmt  'ld-Not made to feel not college material'"
 "lrnknowt  'ld-Not know more than test'"
 "lrnproof  'ld-Not unsure of un-proofed-by-other paper'"
 "lrnrread  'ld-Not read texts 2-3 times to make sense'"
 "lrneffic  'ld-Not more time, lower grades'"
 "lrntestt  'ld-Not test better if more time'"
 "lrntimas  'ld-Not too much time on assignments'"
 "lrntired  'ld-Not reading 1 hour make tired'"
 "lrntanxi  'ld-Not more anxiety about tests'"
 "lrnsmart  'ld-Not smarter than grades indicate'"
 "lrnaread  'ld-Not problem avoiding reading'"
 "lrnrslow  'ld-Not slower reader'"
 "smtbusy  'sm-Rarely upset about too rushed'"
 "smtfutur  'sm-Time planning and distant goals'"
 "smtexerc  'sm-Exercise freq-20 mins'"
 "smteath  'sm-Healthy diet'"
 "smtsleep  'sm-Hours sleep'"
 "smtsdeve  'sm-Managed self-change'"
 "smtnproc  'sm-Start & complete big projects'"
 "smtptodo  'sm-To-do list--all areas'"
 "smtgoals  'sm-Objectives lists used'"
 "smtschd  'sm-Weekly schedule'"
 "smt2dtod  'sm-2-D to-do lists--assignments'"
 "smtacmpl  'sm-High accomplishment, lo pressure'"
 "smtghelp  'sm-Regular self-development habits'"
 "smtbalan  'sm-Life area balance/satisfaction'"
 "smthabch  'sm-Take good advice--make changes'"
 "copnegth  'cp-Not worry, neg thoughts'"
 "copcopea  'cp-Not eat'"
 "coppsolv  'cp-Face & problem solve'"
 "copemota  'cp-Not outward anger'"
 "copavops  'cp-Not avoid thinking about-dealing w/problemNEW'"
 "copblame  'cp-Not blame others or self'"
 "copwdrw  'cp-Not withdraw from others'"
 "copfun  'cp-Fun or involving activity'"
 "coptalks  'cp-Talk about problem'"
 "coppepta  'cp-Positive thoughts-pep talk'"
 "copsmoke  'cp-Not smoke tobacco'"
 "copdrug  'cp-Not drink alcohol, street drugs,or meds'"
 "coppe  'cp-Vigorous physical activity'"
 "copnegph  'cp-Not critical-punative thoughts'"
 "copselfb  'cp-Not anger at self'"
 "copposph  'cp-Phil or religious viewpoint'"
 "copexpec  'cp-Examine expectations'"
 "cophappy  'cp-Think happy no matter what'"
 "copavoat  'cp-Not miss work, school, etc-'"
 "copselfe  'cp-Self-exploration enjoyment'"
 "thm1ach  'ta-Being the best'"
 "thm3educ  'ta-Advanced degrees'"
 "thm4mone  'ta-Very high income'"
 "thm25pos  'ta-High quality possessions'"
 "thm26suc  'ta-Career success'"
 "thmimpac  'ta-Impact-change world'"
 "thm28cre  'ta-Creation-major contribution'"
 "thm30ceo  'ta-Power-ceo, owner'"
 "thm33goa  'ta-Complete all important goals'"
 "thm8roma  'ts-Love-romance'"
 "thm12ple  'ts-Pleasing others-avoid conflict'"
 "thmrespe  'ts-Respect from others'"
 "thm20int  'ts-Intimacy-close relationships'"
 "thmliked  'ts-Well-liked by many'"
 "thmcareg  'ts-Care-giving-parent, others'"
 "thmsuppo  'ts-Emotional support from others'"
 "thmatten  'ts-Attention from others'"
 "thmfamil  'ts-Family'"
 "thmrecog  'ts-Recognition-respect,status,etc'"
 "thmphurt  'td-Personal healing-overcome problems'"
 "thmobgod  'td-Obedience to God'"
 "thmparlv  'td-Parental love and respect'"
 "thmsprot  'td-Self-protection'"
 "thmpunct  'td-Punctuality'"
 "thmoblig  'td-Obligation'"
 "thm5adve  'ti-Adventure'"
 "thm6lear  'ti-Learning, self-development'"
 "thm9shap  'ti-Self-happiness'"
 "thm10oth  'ti-Giving to others happiness, world'"
 "thmrelgd  'ti-Spiritual intimacy'"
 "thm14ind  'ti-Independence'"
 "thm22bod  'ti-Health and longevity'"
 "thm23bal  'ti-Life balance'"
 "thmorder  'ti-Orderliness organization'"
 "thmmench  'ti-Mental Challenge'"
 "thm34exp  'ti-Exploration find answers'"
 "thmcompc  'ti-Competence, best I can be'"
 "thminteg  'ti-Integrity'"
 "thmphil  'ti-Personal philosophy'"
 "thmclean  'ti-Cleanliness'"
 "thmwhole  'ti-Wholeness'"
 "thmperfe  'ti-Perfection and idealism'"
 "thmjusti  'ti-Justice'"
 "thmsimpl  'ti-Simplicity'"
 "thmbeaut  'ti-Beauty'"
 "thmgoodn  'ti-Goodness'"
 "thmuniqu  'ti-Uniqueness & diversity'"
 "thmcreat  'ti-Creativeness'"
 "thmefort  'ti-Effortlessness'"
 "thmplayf  'ti-Fun playfulness'"
 "thmsesuf  'ti-Self-sufficiency'"
 "thmsedis  'ti-Self-discipline'"
 "thmspiri  'ti-God and/or spirituality'"
 "thmrelig  'ti-Religion'"
 "thmuncon  'ti-Unconditional love of all people'"
 "tbvothfi  'bu-Not always others first'"
 "tbvliked  'bu-Not loved by all'"
 "tbvweak  'bu-Not weak and dependent'"
 "tbvbest  'bu-Not must be best'"
 "tbventit  'bu-Not entitled to good life'"
 "tbvrules  'bu-Not if break rules--severe punishment'"
 "tbvwinne  'bu-Not winners and losers'"
 "tbvbalan  'bu-Balance present-future, self-others hap'"
 "tbvhapca  'bu-Decisions-max happiness'"
 "tbvgrati  'bu-Gratitude-abundance thinking'"
 "thvselfa  'bu-Accept all parts of self'"
 "thvselfaORIG  'ORIG-bu-Accept all parts of self'"
 "thvuncon  'bu-Value all unconditionally'"
 "thvselfw  'bu-Value self unconditionally'"
 "iecselfs  'ie-Take care of self & probs'"
 "iecicont  'ie-I control life-happiness'"
 "iecgenet  'ie-Not genetics-biology control my hap'"
 "iecpeopl  'ie-Not others control my happiness'"
 "iecdepen  'ie-Not dependent on one person'"
 "ieccofee  'ie-Not care for another above self'"
 "ieccoprb  'ie-Not worry carrying for one's serious prob'"
 "wovprogr  'wv-World will improve'"
 "wovgoodf  'wv-Good forces control world'"
 "wovmylif  'wv-My life will improve'"
 "wovnfair  'wv-Not life unfair to me'"
 "woventit  'wv-Not entitled to basic necessities'"
 "wovinjur  'wv-Not one ruined my life'"
 "wovabund  'wv-Have all I need to be happy'"
 "wovgrate  'wv-Extremely grateful'"
 "wovposth  'wv-Percent of time positive thoughts'"
 "wovhappy  'wf-Not fear unhappy career'"
 "wovpoor  'wf-Not fear of poverty'"
 "wovill  'wf-Not fear of illness'"
 "wovdeath  'wf-Not fear of death'"
 "wovalone  'wf-Not fear of being alone'"
 "wovnolov  'wf-Not fear of poor marriage-family'"
 "wovliked  'wf-Not fear of not close friends'"
 "wovperso  'wf-Not fear of not being person want'"
 "wovprobl  'wf-Not fear of overcoming problem'"
 "wovdisco  'wf-Not fear of something discovered'"
 "wovsucce  'wf-Not fear of lack acad-career success'"
 "wovoverc  'wf-Could be happy if worst fear happened'"
 "slflearn  'sc-Learning and study skills'"
 "slfcritt  'sc-Critical thinking and logic'"
 "slfresea  'sc-Research & methodology'"
 "slfanaly  'sc-Analytical thinking'"
 "slfsynth  'sc-Synthesis'"
 "slfcreat  'sc-Creative thinking-ideas'"
 "slfcompu  'sc-Computer-related'"
 "slfbiosc  'sc-Biological science'"
 "slfnatsc  'sc-Natural science--physics, chem'"
 "slflibar  'sc-Liberal arts'"
 "slfsocsc  'sc-Beh-social science'"
 "slfphilr  'sc-Philosophy-religion'"
 "slfperfa  'sc-Performing arts'"
 "slffinea  'sc-Fine arts'"
 "slfbusan  'sc-Business or management'"
 "slfheal2  'sc-Health or medicine'"
 "slfengin  'sc-Engineering or technical'"
 "slfeduch  'sc-Educ,Counseling, or helping'"
 "slfiq  'sc-Intelligence'"
 "slfdecma  'sc-Decision-making/planning'"
 "slftimem  'sc-Time management'"
 "slfcope  'sc-Emotional coping skills'"
 "slfself4  'sc-Ach motivation-work habits, focus'"
 "slfselfm  'sc-Self-motivation of unpleasant'"
 "slfachan  'sc-Self-development/change'"
 "slfmana6  'sc-Managing finances'"
 "slfheal3  'sc-Health detailed knowl & habits'"
 "slfmeetp  'sc-Meeting people'"
 "slfliste  'sc-Empathetic listening skills'"
 "slfself5  'sc-Self-disclosure'"
 "slfconfl  'sc-Conflict resolution skills'"
 "slfpersu  'sc-Persuasion skills'"
 "slfmana7  'sc-Management-leadership skills'"
 "slfhelps  'sc-Helping-teaching skills'"
 "slfspeak  'sc-Public speaking skills'"
 "slfjobse  'sc-Job search skills'"
 "slfadapt  'sc-Adaptable-success in any situation'"
 "slfhappy  'sc-Happiness IQ'"
 "slfoptim  'sc-Optimism'"
 "slffrien  'sc-Caring, friendly, outgoing'"
 "slfindep  'sc-Strong, independent, self-disciplined'"
 "cr1issue  'cr-One issue at a time'"
 "crresolv  'cr-Rarely repeat arguments of same issue'"
 "crnthrea  'cr-I rarely make threats'"
 "crunderl  'cr-Discuss underlying issues'"
 "crtklong  'cr-Not one talk long before other'"
 "crnneglb  'cr-I rarely use negative labels'"
 "crteweak  'cr-Not uncomfortable about tell weakness'"
 "crwinwin  'cr-Discuss until win-win solution'"
 "crlongtk  'cr-Keep going until reach a solution'"
 "crexaggr  'cr-I not freq use 'always' or exaggeration'"
 "crmanipu  'cr-Not feel me or partner manipulate'"
 "crsummar  'cr-I repeat summary'"
 "crcprais  'cr-We laugh & praise during disagree'"
 "crboassr  'cr-Both assertive pos,firm,diplom'"
 "crophone  'cr-We open,nondefensive,honest'"
 "crreprai  'cr-Partner gives more praise than criticism'"
 "crteach  'cr-Not problem teaching other'"
 "crifavor  'cr-I do favors cheerfully when asked'"
 "crifolup  'cr-I do what I tell partner'"
 "crangang  'cr-If p-angry at me, I don't get angry-def'"
 "criprais  'cr-I not criticize more than praise p-'"
 "crangres  'cr-If one angry, other assertive back'"
 "crtlkmor  'cr-One partner not much more talkative'"
 "creqwin  'cr-Equal winning of disagreements'"
 "instshlp  'in-Partner helps if I under stress'"
 "intcomit  'in-Not-commitment cause feel trapped'"
 "intundrl  'in-We discuss underlying issues'"
 "inttelal  'in-Told partner all about self'"
 "intsmgoa  'in-We agree on long term goals'"
 "inteqdec  'in-Equality in decision influence'"
 "intiopen  'in-We tell almost exactly what we thinking'"
 "intweopn  'in-We open, nondefensive,honest'"
 "intdaily  'in-Daily sharing of feelings on events'"
 "intrespt  'in-Respect partner above others'"
 "intallop  'in-Open, specific about sensitive issues'"
 "intwktog  'in-We enjoy working together'"
 "intknpfe  'in-Not frequently don't know p- feelings'"
 "intlsqpr  'in-Tell of respect, love of p- to others'"
 "intlove  'in-I love partner very much'"
 "inrbealnORIG  'ORIG-id-OK for weekends alone'"
 "inrbealn  'id-OK for weekends alone'"
 "inalcnstORIG  'ORIG-id-Not consult for small decisions'"
 "inalcnst  'id-Not consult for small decisions'"
 "inrfrien  'id-P- has opposite sex social friends'"
 "indifdec  'id-Support p decision if disagree'"
 "inrlunch  'id-Ok--p - lunch w/ attr- opposite sex'"
 "inrinhap  'id-Marriage not greater than ind- happy'"
 "innevarg  'id-Not-partners never disagree if happy'"
 "inrigrow  'id-I end relationship if can't grow'"
 "inrsaywe  'id-Not say we'when mean 'I'"
 "incomtwo  'id-Not-worries of other's commitment'"
 "indifgoa  'id-Ok for different goals'"
 "infindan  'id-Could be happy with another'"
 "inenalon  'id-Not-can't enjoy being w/o partner'"
 "inokalon  'id-Not-not happy if not partner'"
 "inrhatea  'id-Not-I hate to be alone'"
 "inrfreeh  'id-Free at home if partner there'"
 "insepint  'id-sep-interests'"
 "inrmoney  'id-SeparateFunds'"
 "romsurpr  'ro-Surprise p- once/week'"
 "romfanta  'ro-Freq fantasies about p-'"
 "romceleb  'ro-Celebrate special days 1/month'"
 "romplace  'ro-We go to romantic places 1/week'"
 "romattra  'ro-Sexually attracted to partner'"
 "romplayf  'ro-Some playful interactions weekly'"
 "romcharm  'ro-Partner charming & romantic'"
 "lromtask  'find'"
 "lroftask  'find'"
 "lrmfinal  'find'"
 "lroembar  'find'"
 "lromstro  'find'"
 "lroeqinc  'find'"
 "lrcarcon  'find'"
 "haparea  'h-Happy living in area, home'"
 "hapclfrn  'h-Happy w/ number & closeness of friends'"
 "hapcarnw  'h-Happy w/ my career now'"
 "hapcarfu  'h-Happy w/ future career expectations'"
 "hapfrien  'h-Happy w/ friendships'"
 "hapwkrel  'h-Happy w/ work-school relationships'"
 "happe  'h-Happy w/ physical activity'"
 "haprecre  'h-Happy w/ recreation'"
 "hapsexre  'h-Happy w/ sex/romance'"
 "hapfamil  'h-Happy w/ family relationships'"
 "hapselfd  'h-Happy w/ self & development'"
 "hapspiri  'h-Happy w/ meaning & spiritual/religious'"
 "hapyear  'h-Happiness during past year'"
 "hap3year  'h-Happiness 1-3 years ago'"
 "haplife  'h-Happiness up to 3 years ago'"
 "hapexpec  'h-Happiness expected in future'"
 "rhlfreqi  'he-LoFreq of illness past 3 years'"
 "rhlalcoh  'he-LoFreq of alcohol drinks'"
 "rhlsmoke  'he-LoFreq of cigarrettes'"
 "rhldrugs  'he-LoFreq of illegal drugs'"
 "rhlphysi  'he-Physical conditioning level'"
 "rhlWeigh  'he-LoWeight'"
 "rpehapfr  're-Friends happy-successful'"
 "rpehmarr  're-Have or had happy marital rel'"
 "rpenetw  're-Close network of friends & career-rel'"
 "rpeclfrn  're-Have/had friends share innermost'"
 "rpenumfr  're-Number friends socialize 1/month'"
 "rpenumcl  're-Number extremely close friends'"
 "rpecommi  're-Degree of commit to 3 mo romantic'"
 "rdepfeel  'de-Not often sad,apathetic,depressed'"
 "rdepthou  'de-Not worthless, very neg a-death,etc'"
 "rdepdyss  'de-RevDysthemia symptoms checklist'"
 "rdepmajs  'de-RevMajor depression symptoms chkl'"
 "rdepmeds  'de-RevLength of time meds for depression'"
 "rdepther  'de-RevAmount of therapy for depression'"
 "ranxperf  'ax-RevPerformance anxiety level'"
 "ranxallt  'ax-Not feel anxious almost all time'"
 "ranxpstd  'ax-RevPSTD symptoms chkl'"
 "ranxsoci  'ax-RevAnxiety with other people'"
 "ranxocd  'ax-RevTimes lasting OCD problems'"
 "ranxphob  'ax-RevNumber of phobias'"
 "ranxpani  'ax-RevNumber of panic attacks'"
 "ranxmeds  'ax-RevTime meds for anxiety DEPRESSION?'"
 "ranxther  'ax-Amount of therapy for anxiety'"
 "rangfeel  'ag-RevFreq lose temper'"
 "rangyell  'ag-RevFreq yell or call hurtful names'"
 "rangdomi  'ag-RevFreq get way by [aggression]'"
 "rangthou  'ag-RevFreq think about get even'"
 "rangdest  'ag-RevFreq damage prop etc/break law'"
 "tb2relat  'b2-RevNo absolute right--situational ethics'"
 "tb2punis  'b2-RevBad only happens if bad'"
 "tbv2notr  'b2-RevNot responsible if bad environ/genes'"
 "tb2groum  'b2-RevLife no meaning w/o spec group'"
 "tb2selfm  'b2-RevAll meaning supplied by person'"
 "tb2gdwrk  'b2-RevForgiveness depends on works'"
 "tb2gdatt  'b2-Goodness depends more on attitude'"
 "tb2allgd  'b2-Lots of good in all people'"
 "tb2reaso  'b2-RevScience-reason can solve all worries'"
 "tbv2astr  'b2-RevBelief in spirits,astrology'"
 "tb2idhum  'b2-Identify with all human over any group'"
 "tb2lifad  'b2-Believe in life after death'"
 "tb2movem  'b2-Part of progress greater than family etc'"
 "tbv2core  'b2-Strong phil/rel beliefs guide daily life'"
 "car1carg  'ca-Great time and thorough career plan process'"
 "car1carp  'ca-Have goal,plan,likely success'"
 "car1inat  'ca-Natural science'"
 "caribioh  'ca-Biological science'"
 "carisocs  'ca-Learn about self & people'"
 "carihelp  'ca-Helping people-teach coun etc'"
 "carimath  'ca-Math'"
 "carimed  'ca-Medical-related'"
 "cariwrit  'ca-Writing-related'"
 "carifnar  'ca-Fine art-related'"
 "cariethn  'ca-Ethnic studies-women'"
 "carilear  'ca-Love higher ed'"
 "cariexpe  'ca-Want to be expert'"
 "carigene  'ca-Love variety-know little about many'"
 "carinoin  'ca-Never interest in school'"
 "carilit  'ca-Literature-history'"
 "carirecp  'ca-Sports-rec helping others w/sports'"
 "caripoli  'ca-Law politics government'"
 "carimil6  'ca-Law enforcement military etc'"
 "carimanu  'ca-Manual-tech electr computers etc-'"
 "carilang  'ca-Languages travel etc'"
 "cariphil  'ca-Philosophy-religion'"
 "caribusi  'ca-Business'"
 "cariengi  'ca-Engineering sci design'"
 "carifamc  'ca-Family & Consumer Sci'"
 "cariwoma  'ca-Ethnic-women'"
 "caricom8  'ca-Computer-related'"
 "carinte0  'ca-Interdisciplinary'"
 "caribmar  'cb-Marketing'"
 "caribman  'cb-Management'"
 "caribinf  'cb-Inform Systems'"
 "caribfin  'cb-Finance'"
 "caribhrd  'cb-Human Resources'"
 "caribacc  'cb-Accounting'"
 "carispbu  'cb-Public Relations'"
 "carieeng  'ce-Elect Engr'"
 "carime  'ce-Mech Engr'"
 "cariche2  'ce-Chem Engr'"
 "caricive  'ce-Cival Engr'"
 "cariaero  'ce-Aerospace Engr'"
 "carieite  'ce-Engr Tech'"
 "caricom9  'ce-Computer Engr'"
 "caribcom  'ce-Bus Computer'"
 "carimusi  'cart-Music'"
 "cariart  'cart-Art'"
 "caridram  'cart-Theatre Arts'"
 "caridanc  'cart-Dance'"
 "cariphot  'cart-Photog or Ph Journ'"
 "carindde  'cart-Indust Design'"
 "carinte1  'cart-Interior Design'"
 "cariteac  'ch-Teaching'"
 "caricoun  'ch-Counseling'"
 "carieduc  'ch-Education'"
 "carihadu  'ch-Help Adults'"
 "carihchi  'ch-Help children-teens'"
 "caritvoc  'ch-Voc Ed'"
 "caricom4  'ch-Speech-hearing'"
 "carsocwo  'ch-Social Work'"
 "cark12te  'ch-Teach K-12'"
 "carminis  'ch-Minister-priest'"
 "carifren  'cl-French'"
 "cariital  'cl-Italian'"
 "carigerm  'cl-German'"
 "cariruss  'cl-Russian'"
 "carijapn  'cl-Japanese'"
 "carichin  'cl-Chinese'"
 "cariclas  'cl-Classic Lang'"
 "carispan  'cl-Spanish'"
 "caripor  'cl-Portugese'"
 "carimd  'cm-Physician'"
 "carinurs  'cm-Nurse'"
 "caripthe  'cm-Phys Therapy'"
 "cariheal  'cm-Health Science'"
 "carikine  'cm-Kinesiology'"
 "caricom5  'cm-Commicative Dis'"
 "carmedte  'cm-Med Tech/imaging'"
 "carilaw  'cleg-Law'"
 "caricrim  'cleg-Law enforcement'"
 "carimil7  'cleg-Military'"
 "cariche3  'cn-Chemistry'"
 "cariphys  'cn-Physics'"
 "carigeol  'cn-Geology'"
 "cariastr  'cn-Astronomy'"
 "carienvi  'cn-Environmental Sci'"
 "caripsyc  'cs-Psychology'"
 "carisoco  'cs-Sociology'"
 "carihist  'cs-History'"
 "caripols  'cs-Political Science'"
 "cariecon  'cs-Economics'"
 "cargeogr  'cs-Geography'"
 "cariamer  'cs-American Studies'"
 "cariantr  'cs-Anthropology???-AntR not AntH'"
 "carianth  'cs-Anthropology'"
 "carispee  'cs-Speech-Commun'"
 "carling  'cs-Linguistics'"
 "cariaist  'cs-Native Amer Studies'"
 "caribstu  'cs-African Amer Studies'"
 "carimexa  'cs-Mexican Amer Studies'"
 "cariasam  'cs-Asian Amer Studies'"
 "cariamst  'cs-American Studies'"
 "cariwstu  'cs-Women's Studies'"
 "cariengl  'cw-English'"
 "carijour  'cw-Journalism'"
 "UserRate  'UserRate'")


;;XXX -------------------------------------------------------------------------
;; FROM: (get-all-shaq-variables)

("CaseNum"
 "CaseType"
 "SourceFile"
 "FileDate"
 "Instr"
 "Resr"
 "Name"
 "UserID"
 "Sex"
 "Age"
 "Email"
 "ZipCode"
 "Nation"
 "HrsWork"
 "utype"
 "twanttho"
 "tknowmor"
 "twanthel"
 "twantspe"
 "texperie"
 "tprevshaq"
 "wantspq"
 "tu100stu"
 "tcsulbst"
 "tcolstu"
 "totherst"
 "tressub"
 "tcolfaca"
 "u-none"
 "ugoals"
 "gsuchap"
 "gemocop"
 "gslfest"
 "gprocrst"
 "gtimeman"
 "grelat"
 "gmeetpeo"
 "glonelyf"
 "gexvalus"
 "gdepres"
 "ganxfear"
 "gaggrang"
 "gacadsuc"
 "gcomplta1"
 "gcompltanomaj"
 "gcompltanoac"
 "gcarplan"
 "gcaronly"
 "gnottake"
 "scalessel"
 "xhqonly"
 "xhq-acad"
 "xhq-acad-car"
 "xvalues-th"
 "xworldview"
 "xsel-f-bels"
 "xiecontrol"
 "xselfconf"
 "xselfman"
 "xemotcop"
 "xinterpers"
 "xacadlearn"
 "xcarint"
 "xsehappy"
 "xsrdepres"
 "xsranxiet"
 "xsrangagg"
 "bio3educ"
 "biohsgpa"
 "biocolle"
 "bio4job"
 "student"
 "manager"
 "propeop"
 "protech"
 "consulta"
 "educator"
 "sales"
 "technici"
 "clerical"
 "service"
 "ownbus10"
 "othrsfem"
 "other"
 "bio7lang"
 "lenglish"
 "lspanish"
 "lvietnam"
 "lcambodn"
 "lchinese"
 "lkorean"
 "lportugu"
 "lgerman"
 "lfrench"
 "lothrasn"
 "lothreur"
 "lother"
 "bio1ethn"
 "enortham"
 "eafrica"
 "enoreur"
 "esoueur"
 "ecambodn"
 "echina"
 "ekorea"
 "ejapan"
 "evietnam"
 "eothrasn"
 "emexico"
 "ecentram"
 "esoutham"
 "epacific"
 "eother"
 "biorelaf"
 "catholic"
 "jewish"
 "latterd"
 "buddhist"
 "baptist"
 "methodst"
 "episcop"
 "lutheran"
 "presbyte"
 "proliber"
 "profunda"
 "noaffil"
 "agnostic"
 "othrnoan"
 "family"
 "OlderBrN"
 "OlderSisN"
 "YoungBrN"
 "YoungSisN"
 "Raised2Parents"
 "SingleMparent"
 "SingleFparent"
 "RaisedNoParents"
 "RaisedOther"
 "bio5inco"
 "stucolle"
 "cocsulb"
 "cccsu"
 "coucal"
 "coopublc"
 "coprivca"
 "coprivot"
 "cocacomc"
 "coothcc"
 "coothnat"
 "coprgrad"
 "cotech"
 "highsch"
 "coother"
 "stumajor"
 "mlibart"
 "msocsci"
 "mbiolsci"
 "mart"
 "mnatsci"
 "mbus"
 "menginr"
 "meducat"
 "mmedical"
 "motcompu"
 "mothtech"
 "mrecrpe"
 "mdoesna"
 "mundecid"
 "stuspeci"
 "strancc"
 "stran4yr"
 "sadultre"
 "seop"
 "susimmig"
 "svisa"
 "shonor"
 "svisastu"
 "sdisabld"
 "soutofst"
 "smilitar"
 "sathlete"
 "snone"
 "sturesid"
 "rsinwpar"
 "rsindorm"
 "rsinwchl"
 "rsinothr"
 "rmarwoch"
 "rmarwchl"
 "rmarlike"
 "rother"
 "stpared"
 "stuclass"
 "studegre"
 "stusemes"
 "stmajgpa"
 "stacadst"
 "stgpatre"
 "trconhi"
 "trincryr"
 "trincyru"
 "trincyrs"
 "trgradin"
 "trconave"
 "trdecyru"
 "trdecyr"
 "trconlow"
 "trupandd"
 "trother"
 "stuverba"
 "stumatha"
 "stulookf"
 "stulikei"
 "stucomfo"
 "stufrien"
 "stuextmo"
 "stuenjoy"
 "stucaree"
 "stumoney"
 "stuconfu"
 "stufinde"
 "stueactr"
 "sthapcol"
 "sthapgpa"
 "sturesource"
 "afinanc"
 "afampres"
 "afamresp"
 "aworktim"
 "awrkpres"
 "arelprob"
 "aloneli"
 "ahomstpl"
 "aschstpl"
 "acompavl"
 "awrngcls"
 "afacconn"
 "astuconn"
 "alowmotv"
 "atimconf"
 "aprocras"
 "acmstudy"
 "acmndrop"
 "acmatten"
 "acmefaml"
 "acmesocs"
 "acmconce"
 "acmtime"
 "acmtimeORIG"
 "acmselfs"
 "acmcompl"
 "acmquitc"
 "acmfinan"
 "acmdegre"
 "lrnestud"
 "lrntxove"
 "lrntxund"
 "lrntsrev"
 "lrnmap"
 "lrntextn"
 "lrninter"
 "lrnrote"
 "lrnassoc"
 "lrnstrug"
 "lrntheor"
 "lrnalone"
 "lrnmath"
 "lrnwrpap"
 "lrntxout"
 "lrnnotes"
 "lrnwrskl"
 "lrnsee"
 "lrnvocab"
 "lrnsread"
 "lrnmemor"
 "lrntense"
 "lrnsefic"
 "lrnwrorg"
 "lrnunasn"
 "lrncolmt"
 "lrnknowt"
 "lrnproof"
 "lrnrread"
 "lrneffic"
 "lrntestt"
 "lrntimas"
 "lrntired"
 "lrntanxi"
 "lrnsmart"
 "lrnaread"
 "lrnrslow"
 "smtbusy"
 "smtfutur"
 "smtexerc"
 "smteath"
 "smtsleep"
 "smtsdeve"
 "smtnproc"
 "smtptodo"
 "smtgoals"
 "smtschd"
 "smt2dtod"
 "smtacmpl"
 "smtghelp"
 "smtbalan"
 "smthabch"
 "copnegth"
 "copcopea"
 "coppsolv"
 "copemota"
 "copavops"
 "copblame"
 "copwdrw"
 "copfun"
 "coptalks"
 "coppepta"
 "copsmoke"
 "copdrug"
 "coppe"
 "copnegph"
 "copselfb"
 "copposph"
 "copexpec"
 "cophappy"
 "copavoat"
 "copselfe"
 "thm1ach"
 "thm3educ"
 "thm4mone"
 "thm25pos"
 "thm26suc"
 "thmimpac"
 "thm28cre"
 "thm30ceo"
 "thm33goa"
 "thm8roma"
 "thm12ple"
 "thmrespe"
 "thm20int"
 "thmliked"
 "thmcareg"
 "thmsuppo"
 "thmatten"
 "thmfamil"
 "thmrecog"
 "thmphurt"
 "thmobgod"
 "thmparlv"
 "thmsprot"
 "thmpunct"
 "thmoblig"
 "thm5adve"
 "thm6lear"
 "thm9shap"
 "thm10oth"
 "thmrelgd"
 "thm14ind"
 "thm22bod"
 "thm23bal"
 "thmorder"
 "thmmench"
 "thm34exp"
 "thmcompc"
 "thminteg"
 "thmphil"
 "thmclean"
 "thmwhole"
 "thmperfe"
 "thmjusti"
 "thmsimpl"
 "thmbeaut"
 "thmgoodn"
 "thmuniqu"
 "thmcreat"
 "thmefort"
 "thmplayf"
 "thmsesuf"
 "thmsedis"
 "thmspiri"
 "thmrelig"
 "thmuncon"
 "tbvothfi"
 "tbvliked"
 "tbvweak"
 "tbvbest"
 "tbventit"
 "tbvrules"
 "tbvwinne"
 "tbvbalan"
 "tbvhapca"
 "tbvgrati"
 "thvselfa"
 "thvselfaORIG"
 "thvuncon"
 "thvselfw"
 "iecselfs"
 "iecicont"
 "iecgenet"
 "iecpeopl"
 "iecdepen"
 "ieccofee"
 "ieccoprb"
 "wovprogr"
 "wovgoodf"
 "wovmylif"
 "wovnfair"
 "woventit"
 "wovinjur"
 "wovabund"
 "wovgrate"
 "wovposth"
 "wovhappy"
 "wovpoor"
 "wovill"
 "wovdeath"
 "wovalone"
 "wovnolov"
 "wovliked"
 "wovperso"
 "wovprobl"
 "wovdisco"
 "wovsucce"
 "wovoverc"
 "slflearn"
 "slfcritt"
 "slfresea"
 "slfanaly"
 "slfsynth"
 "slfcreat"
 "slfcompu"
 "slfbiosc"
 "slfnatsc"
 "slflibar"
 "slfsocsc"
 "slfphilr"
 "slfperfa"
 "slffinea"
 "slfbusan"
 "slfheal2"
 "slfengin"
 "slfeduch"
 "slfiq"
 "slfdecma"
 "slftimem"
 "slfcope"
 "slfself4"
 "slfselfm"
 "slfachan"
 "slfmana6"
 "slfheal3"
 "slfmeetp"
 "slfliste"
 "slfself5"
 "slfconfl"
 "slfpersu"
 "slfmana7"
 "slfhelps"
 "slfspeak"
 "slfjobse"
 "slfadapt"
 "slfhappy"
 "slfoptim"
 "slffrien"
 "slfindep"
 "cr1issue"
 "crresolv"
 "crnthrea"
 "crunderl"
 "crtklong"
 "crnneglb"
 "crteweak"
 "crwinwin"
 "crlongtk"
 "crexaggr"
 "crmanipu"
 "crsummar"
 "crcprais"
 "crboassr"
 "crophone"
 "crreprai"
 "crteach"
 "crifavor"
 "crifolup"
 "crangang"
 "criprais"
 "crangres"
 "crtlkmor"
 "creqwin"
 "instshlp"
 "intcomit"
 "intundrl"
 "inttelal"
 "intsmgoa"
 "inteqdec"
 "intiopen"
 "intweopn"
 "intdaily"
 "intrespt"
 "intallop"
 "intwktog"
 "intknpfe"
 "intlsqpr"
 "intlove"
 "inrbealnORIG"
 "inrbealn"
 "inalcnstORIG"
 "inalcnst"
 "inrfrien"
 "indifdec"
 "inrlunch"
 "inrinhap"
 "innevarg"
 "inrigrow"
 "inrsaywe"
 "incomtwo"
 "indifgoa"
 "infindan"
 "inenalon"
 "inokalon"
 "inrhatea"
 "inrfreeh"
 "insepint"
 "inrmoney"
 "romsurpr"
 "romfanta"
 "romceleb"
 "romplace"
 "romattra"
 "romplayf"
 "romcharm"
 "lromtask"
 "lroftask"
 "lrmfinal"
 "lroembar"
 "lromstro"
 "lroeqinc"
 "lrcarcon"
 "haparea"
 "hapclfrn"
 "hapcarnw"
 "hapcarfu"
 "hapfrien"
 "hapwkrel"
 "happe"
 "haprecre"
 "hapsexre"
 "hapfamil"
 "hapselfd"
 "hapspiri"
 "hapyear"
 "hap3year"
 "haplife"
 "hapexpec"
 "rhlfreqi"
 "rhlalcoh"
 "rhlsmoke"
 "rhldrugs"
 "rhlphysi"
 "rhlWeigh"
 "rpehapfr"
 "rpehmarr"
 "rpenetw"
 "rpeclfrn"
 "rpenumfr"
 "rpenumcl"
 "rpecommi"
 "rdepfeel"
 "rdepthou"
 "rdepdyss"
 "rdepmajs"
 "rdepmeds"
 "rdepther"
 "ranxperf"
 "ranxallt"
 "ranxpstd"
 "ranxsoci"
 "ranxocd"
 "ranxphob"
 "ranxpani"
 "ranxmeds"
 "ranxther"
 "rangfeel"
 "rangyell"
 "rangdomi"
 "rangthou"
 "rangdest"
 "tb2relat"
 "tb2punis"
 "tbv2notr"
 "tb2groum"
 "tb2selfm"
 "tb2gdwrk"
 "tb2gdatt"
 "tb2allgd"
 "tb2reaso"
 "tbv2astr"
 "tb2idhum"
 "tb2lifad"
 "tb2movem"
 "tbv2core"
 "car1carg"
 "car1carp"
 "car1inat"
 "caribioh"
 "carisocs"
 "carihelp"
 "carimath"
 "carimed"
 "cariwrit"
 "carifnar"
 "cariethn"
 "carilear"
 "cariexpe"
 "carigene"
 "carinoin"
 "carilit"
 "carirecp"
 "caripoli"
 "carimil6"
 "carimanu"
 "carilang"
 "cariphil"
 "caribusi"
 "cariengi"
 "carifamc"
 "cariwoma"
 "caricom8"
 "carinte0"
 "caribmar"
 "caribman"
 "caribinf"
 "caribfin"
 "caribhrd"
 "caribacc"
 "carispbu"
 "carieeng"
 "carime"
 "cariche2"
 "caricive"
 "cariaero"
 "carieite"
 "caricom9"
 "caribcom"
 "carimusi"
 "cariart"
 "caridram"
 "caridanc"
 "cariphot"
 "carindde"
 "carinte1"
 "cariteac"
 "caricoun"
 "carieduc"
 "carihadu"
 "carihchi"
 "caritvoc"
 "caricom4"
 "carsocwo"
 "cark12te"
 "carminis"
 "carifren"
 "cariital"
 "carigerm"
 "cariruss"
 "carijapn"
 "carichin"
 "cariclas"
 "carispan"
 "caripor"
 "carimd"
 "carinurs"
 "caripthe"
 "cariheal"
 "carikine"
 "caricom5"
 "carmedte"
 "carilaw"
 "caricrim"
 "carimil7"
 "cariche3"
 "cariphys"
 "carigeol"
 "cariastr"
 "carienvi"
 "caripsyc"
 "carisoco"
 "carihist"
 "caripols"
 "cariecon"
 "cargeogr"
 "cariamer"
 "cariantr"
 "carianth"
 "carispee"
 "carling"
 "cariaist"
 "caribstu"
 "carimexa"
 "cariasam"
 "cariamst"
 "cariwstu"
 "cariengl"
 "carijour"
 "UserRate"
 "ST1HIGHERSELF"
 "ST2SOCINTIMNOFAM"
 "ST3FAMCARE"
 "ST4SUCCESSSTATUSMATER"
 "ST5-ORDERPERFECTIONGOODNESS"
 "ST6GODSPIRITRELIG"
 "ST7IMPACTCHALLENGEEXPLOR"
 "ST8ATTENTIONFUNEASY"
 "ST9VALUESELFALLUNCOND"
 "ST10OVERCMPROBACCEPTSELF"
 "ST11DUTYPUNCTUAL"
 "SWORLDVIEW"
 "STBSLFWO"
 "SIECONTR"
 "SETHBEL"
 "SGRFEARS"
 "SSLFCONF"
 "SSELFMAN"
 "SEMOTCOP"
 "INTSS1AASSERTCR"
 "INTSS1BOPENHON"
 "INTSS2ROMANTC"
 "INTSS3LIBROLE"
 "INTSS4LOVERES"
 "INTSS5INDEP"
 "INTSS6POSSUP"
 "INTSS7COLLAB"
 "SCOLLEGE"
 "SSL1CONFIDEFFICSTUDYTEST"
 "SSL1BCONFIDNOTAVOIDSTUDY"
 "SSL2SATISCAMPUSFACFRIENDSGRDES"
 "SSL3WRITINGSKILLS"
 "SSL4BLDMENTALSTRUCT"
 "SSL5BASICSTUDYSKILLS"
 "SSL6SELFMANACADGOALS"
 "SSL7MATHSCIPRINC"
 "SSL8STUDYENVIR"
 "SSL9ATTENDHW"
 "SSL10MEMNOTANX"
 "SSL11NOTNONACADMOT"
 "SSL12STDYTMAVAIL"
 "SSL13VERBALAPT"
 "SSL14MATHAPT"
 "SINCAR"
 "SINBUS"
 "SINENGR"
 "SINFINEA"
 "SINHELP"
 "SINLANG"
 "SINMED"
 "SINMILTC"
 "INNATSCI"
 "SINSOCSC"
 "SINWOETH"
 "SINWRITE"
 "SEHAPPY"
 "SRDEPRES"
 "SRANXIET"
 "SRANGAGG"
 "SRELHLTH"
 "SRPEOPLE"
 "SSWVGRATPT"
 "SSWVOPTIMS"
 "SSWVENTIT"
 "SSSWNONCONT"
 "SSSWHAPALLGRAT"
 "SSSWACALLSELF"
 "SSIEAUTONY"
 "SSIENCODEP"
 "SSIENOTHER"
 "SSB2ETHIC"
 "SSB2FORGIV"
 "SSB2IDGRND"
 "SSB2GRNDMNG"
 "SSB2INRGOOD"
 "SSB2NOASTR"
 "SSB2LIFAD"
 "SSWFSOCIAL"
 "SSWFSELF"
 "SSWFPOVFAI"
 "SSWFILLDEA"
 "SSSCLEARN"
 "SSSCCOPOPT"
 "SSSCSMSMSD"
 "SSSCINTERP"
 "SSSCALLHELP"
 "SSSCSCIENCE"
 "SSSCARTCRE"
 "SSSMTIMEMANGOALSET"
 "SSSMACCOMPLORUSH"
 "SSSMSELFDEVEL"
 "SSSMHEALTHHABS"
 "SSCPPROBSOLV"
 "SSCPPOSTHOUGHTS"
 "SSCPPOSACTS"
 "SSCPNOBLAMEANGERWDRAW"
 "SSCPNOTSMOKDRUGMED"
 "SSCPNOTEAT"
 "HAPSDMEANSPIRITSS"
 "HAPCAREEREXSS"
 "HAPRECPESS"
 "HAPAREASS"
 "HAPFAMSS"
 "HAPROMSS"
 "HAPFRIENDSSS"
 "HAPFUTURESS"
 "HAPPASTSS"
 "HAPRECENTSS"
 "SSRECLOSEFRIENDS"
 "SSREROMRELSUC"
 "SSRENUMFRIENDS"
 "SSREHAPSUCFRS"
 "SSDELODEPSYMP"
 "SSDELODEPTREATS"
 "SSAXLOPERFGENANX"
 "SSAXLOWFEAROCD"
 "SSAXLOANXTREATS"
 "SSHELONEGADDICTHABS"
 "SSHELOFREQILL"
 "SSHEPELOWEIGHT")

