
(DEFPARAMETER *BIO-INST (MAKE-INSTANCE 'BIO))

(DEFPARAMETER *VALUES-THEMES-INST (MAKE-INSTANCE 'VALUES-THEMES))

(DEFPARAMETER *BELIEFS-INST (MAKE-INSTANCE 'BELIEFS))

(DEFPARAMETER *SKILLS-CONFIDENCE-INST (MAKE-INSTANCE
                                       'SKILLS-CONFIDENCE))

(DEFPARAMETER *INTERPERSONAL-INST (MAKE-INSTANCE 'INTERPERSONAL))

(DEFPARAMETER *ACAD-LEARNING-INST (MAKE-INSTANCE 'ACAD-LEARNING))

(DEFPARAMETER *CAREER-INTEREST-INST (MAKE-INSTANCE 'CAREER-INTEREST))

(DEFPARAMETER *OUTCOME-INST (MAKE-INSTANCE 'OUTCOME))

(DEFPARAMETER *BIO-TEXT-INST (MAKE-INSTANCE 'BIO-TEXT))

(DEFPARAMETER *INTRO-MAQ-INST (MAKE-INSTANCE 'INTRO-MAQ))

(DEFPARAMETER *BIO-MAQ-INST (MAKE-INSTANCE 'BIO-MAQ))

(DEFPARAMETER *HQ-INST (MAKE-INSTANCE 'HQ))

(DEFPARAMETER *HIGHERSELFSCALE-INST (MAKE-INSTANCE 'HIGHERSELFSCALE))

(DEFPARAMETER *SID-INST (MAKE-INSTANCE 'SID))

(DEFPARAMETER *ACAD-ACH-INST (MAKE-INSTANCE 'ACAD-ACH))

(DEFPARAMETER *NO-SCALE-INST (MAKE-INSTANCE 'NO-SCALE))

(DEFPARAMETER *SUTYPE-INST (MAKE-INSTANCE 'SUTYPE))

(DEFPARAMETER *SUGOALS-INST (MAKE-INSTANCE 'SUGOALS))

(DEFPARAMETER *ST1HIGHERSELF-INST (MAKE-INSTANCE 'ST1HIGHERSELF))

(DEFPARAMETER *ST2SOCINTIMNOFAM-INST (MAKE-INSTANCE 'ST2SOCINTIMNOFAM))

(DEFPARAMETER *ST3FAMCARE-INST (MAKE-INSTANCE 'ST3FAMCARE))

(DEFPARAMETER *ST4SUCCESSSTATUSMATER-INST (MAKE-INSTANCE
                                           'ST4SUCCESSSTATUSMATER))

(DEFPARAMETER *ST5-ORDERPERFECTIONGOODNESS-INST (MAKE-INSTANCE
                                                 'ST5-ORDERPERFECTIONGOODNESS))

(DEFPARAMETER *ST6GODSPIRITRELIG-INST (MAKE-INSTANCE
                                       'ST6GODSPIRITRELIG))

(DEFPARAMETER *ST7IMPACTCHALLENGEEXPLOR-INST (MAKE-INSTANCE
                                              'ST7IMPACTCHALLENGEEXPLOR))

(DEFPARAMETER *ST8ATTENTIONFUNEASY-INST (MAKE-INSTANCE
                                         'ST8ATTENTIONFUNEASY))

(DEFPARAMETER *ST9VALUESELFALLUNCOND-INST (MAKE-INSTANCE
                                           'ST9VALUESELFALLUNCOND))

(DEFPARAMETER *ST10OVERCMPROBACCEPTSELF-INST (MAKE-INSTANCE
                                              'ST10OVERCMPROBACCEPTSELF))

(DEFPARAMETER *ST11DUTYPUNCTUAL-INST (MAKE-INSTANCE 'ST11DUTYPUNCTUAL))

(DEFPARAMETER *SWORLDVIEW-INST (MAKE-INSTANCE 'SWORLDVIEW))

(DEFPARAMETER *STBSLFWO-INST (MAKE-INSTANCE 'STBSLFWO))

(DEFPARAMETER *SIECONTR-INST (MAKE-INSTANCE 'SIECONTR))

(DEFPARAMETER *SETHBEL-INST (MAKE-INSTANCE 'SETHBEL))

(DEFPARAMETER *SGRFEARS-INST (MAKE-INSTANCE 'SGRFEARS))

(DEFPARAMETER *SSLFCONF-INST (MAKE-INSTANCE 'SSLFCONF))

(DEFPARAMETER *SSELFMAN-INST (MAKE-INSTANCE 'SSELFMAN))

(DEFPARAMETER *SEMOTCOP-INST (MAKE-INSTANCE 'SEMOTCOP))

(DEFPARAMETER *INTSS1AASSERTCR-INST (MAKE-INSTANCE 'INTSS1AASSERTCR))

(DEFPARAMETER *INTSS1BOPENHON-INST (MAKE-INSTANCE 'INTSS1BOPENHON))

(DEFPARAMETER *INTSS2ROMANTC-INST (MAKE-INSTANCE 'INTSS2ROMANTC))

(DEFPARAMETER *INTSS3LIBROLE-INST (MAKE-INSTANCE 'INTSS3LIBROLE))

(DEFPARAMETER *INTSS4LOVERES-INST (MAKE-INSTANCE 'INTSS4LOVERES))

(DEFPARAMETER *INTSS5INDEP-INST (MAKE-INSTANCE 'INTSS5INDEP))

(DEFPARAMETER *INTSS6POSSUP-INST (MAKE-INSTANCE 'INTSS6POSSUP))

(DEFPARAMETER *INTSS7COLLAB-INST (MAKE-INSTANCE 'INTSS7COLLAB))

(DEFPARAMETER *SCOLLEGE-INST (MAKE-INSTANCE 'SCOLLEGE))

(DEFPARAMETER *SSL1CONFIDEFFICSTUDYTEST-INST (MAKE-INSTANCE
                                              'SSL1CONFIDEFFICSTUDYTEST))

(DEFPARAMETER *SSL1BCONFIDNOTAVOIDSTUDY-INST (MAKE-INSTANCE
                                              'SSL1BCONFIDNOTAVOIDSTUDY))

(DEFPARAMETER *SSL2SATISCAMPUSFACFRIENDSGRDES-INST (MAKE-INSTANCE
                                                    'SSL2SATISCAMPUSFACFRIENDSGRDES))

(DEFPARAMETER *SSL3WRITEREADSKILLS-INST (MAKE-INSTANCE
                                         'SSL3WRITEREADSKILLS))

(DEFPARAMETER *SSL4BLDMENTALSTRUCT-INST (MAKE-INSTANCE
                                         'SSL4BLDMENTALSTRUCT))

(DEFPARAMETER *SSL5BASICSTUDYSKILLS-INST (MAKE-INSTANCE
                                          'SSL5BASICSTUDYSKILLS))

(DEFPARAMETER *SSL6SELFMANACADGOALS-INST (MAKE-INSTANCE
                                          'SSL6SELFMANACADGOALS))

(DEFPARAMETER *SSL7MATHSCIPRINC-INST (MAKE-INSTANCE 'SSL7MATHSCIPRINC))

(DEFPARAMETER *SSL8STUDYENVIR-INST (MAKE-INSTANCE 'SSL8STUDYENVIR))

(DEFPARAMETER *SSL9ATTENDHW-INST (MAKE-INSTANCE 'SSL9ATTENDHW))

(DEFPARAMETER *SSL10MEMNOTANX-INST (MAKE-INSTANCE 'SSL10MEMNOTANX))

(DEFPARAMETER *SSL11NOTNONACADMOT-INST (MAKE-INSTANCE
                                        'SSL11NOTNONACADMOT))

(DEFPARAMETER *SSL12STDYTMAVAIL-INST (MAKE-INSTANCE 'SSL12STDYTMAVAIL))

(DEFPARAMETER *SSL13VERBALAPT-INST (MAKE-INSTANCE 'SSL13VERBALAPT))

(DEFPARAMETER *SSL14MATHAPT-INST (MAKE-INSTANCE 'SSL14MATHAPT))

(DEFPARAMETER *SINCAR-INST (MAKE-INSTANCE 'SINCAR))

(DEFPARAMETER *SINBUS-INST (MAKE-INSTANCE 'SINBUS))

(DEFPARAMETER *SINENGR-INST (MAKE-INSTANCE 'SINENGR))

(DEFPARAMETER *SINFINEA-INST (MAKE-INSTANCE 'SINFINEA))

(DEFPARAMETER *SINHELP-INST (MAKE-INSTANCE 'SINHELP))

(DEFPARAMETER *SINLANG-INST (MAKE-INSTANCE 'SINLANG))

(DEFPARAMETER *SINMED-INST (MAKE-INSTANCE 'SINMED))

(DEFPARAMETER *SINMILTC-INST (MAKE-INSTANCE 'SINMILTC))

(DEFPARAMETER *INNATSCI-INST (MAKE-INSTANCE 'INNATSCI))

(DEFPARAMETER *SINSOCSC-INST (MAKE-INSTANCE 'SINSOCSC))

(DEFPARAMETER *SINWOETH-INST (MAKE-INSTANCE 'SINWOETH))

(DEFPARAMETER *SINWRITE-INST (MAKE-INSTANCE 'SINWRITE))

(DEFPARAMETER *SEHAPPY-INST (MAKE-INSTANCE 'SEHAPPY))

(DEFPARAMETER *SRDEPRES-INST (MAKE-INSTANCE 'SRDEPRES))

(DEFPARAMETER *SRANXIET-INST (MAKE-INSTANCE 'SRANXIET))

(DEFPARAMETER *SRANGAGG-INST (MAKE-INSTANCE 'SRANGAGG))

(DEFPARAMETER *SRELHLTH-INST (MAKE-INSTANCE 'SRELHLTH))

(DEFPARAMETER *SRPEOPLE-INST (MAKE-INSTANCE 'SRPEOPLE))

(DEFPARAMETER *SSWVGRATPT-INST (MAKE-INSTANCE 'SSWVGRATPT))

(DEFPARAMETER *SSWVOPTIMS-INST (MAKE-INSTANCE 'SSWVOPTIMS))

(DEFPARAMETER *SSWVENTIT-INST (MAKE-INSTANCE 'SSWVENTIT))

(DEFPARAMETER *SSSWNONCONT-INST (MAKE-INSTANCE 'SSSWNONCONT))

(DEFPARAMETER *SSSWHAPALLGRAT-INST (MAKE-INSTANCE 'SSSWHAPALLGRAT))

(DEFPARAMETER *SSSWACALLSELF-INST (MAKE-INSTANCE 'SSSWACALLSELF))

(DEFPARAMETER *SSIEAUTONY-INST (MAKE-INSTANCE 'SSIEAUTONY))

(DEFPARAMETER *SSIENCODEP-INST (MAKE-INSTANCE 'SSIENCODEP))

(DEFPARAMETER *SSIENOTHER-INST (MAKE-INSTANCE 'SSIENOTHER))

(DEFPARAMETER *SSB2ETHIC-INST (MAKE-INSTANCE 'SSB2ETHIC))

(DEFPARAMETER *SSB2FORGIV-INST (MAKE-INSTANCE 'SSB2FORGIV))

(DEFPARAMETER *SSB2IDGRND-INST (MAKE-INSTANCE 'SSB2IDGRND))

(DEFPARAMETER *SSB2GRNDMNG-INST (MAKE-INSTANCE 'SSB2GRNDMNG))

(DEFPARAMETER *SSB2INRGOOD-INST (MAKE-INSTANCE 'SSB2INRGOOD))

(DEFPARAMETER *SSB2NOASTR-INST (MAKE-INSTANCE 'SSB2NOASTR))

(DEFPARAMETER *SSB2LIFAD-INST (MAKE-INSTANCE 'SSB2LIFAD))

(DEFPARAMETER *SSWFSOCIAL-INST (MAKE-INSTANCE 'SSWFSOCIAL))

(DEFPARAMETER *SSWFSELF-INST (MAKE-INSTANCE 'SSWFSELF))

(DEFPARAMETER *SSWFPOVFAI-INST (MAKE-INSTANCE 'SSWFPOVFAI))

(DEFPARAMETER *SSWFILLDEA-INST (MAKE-INSTANCE 'SSWFILLDEA))

(DEFPARAMETER *SSSCLEARN-INST (MAKE-INSTANCE 'SSSCLEARN))

(DEFPARAMETER *SSSCCOPOPT-INST (MAKE-INSTANCE 'SSSCCOPOPT))

(DEFPARAMETER *SSSCSMSMSD-INST (MAKE-INSTANCE 'SSSCSMSMSD))

(DEFPARAMETER *SSSCINTERP-INST (MAKE-INSTANCE 'SSSCINTERP))

(DEFPARAMETER *SSSCALLHELP-INST (MAKE-INSTANCE 'SSSCALLHELP))

(DEFPARAMETER *SSSCSCIENCE-INST (MAKE-INSTANCE 'SSSCSCIENCE))

(DEFPARAMETER *SSSCARTCRE-INST (MAKE-INSTANCE 'SSSCARTCRE))

(DEFPARAMETER *SSSMTIMEMANGOALSET-INST (MAKE-INSTANCE
                                        'SSSMTIMEMANGOALSET))

(DEFPARAMETER *SSSMACCOMPLORUSH-INST (MAKE-INSTANCE 'SSSMACCOMPLORUSH))

(DEFPARAMETER *SSSMSELFDEVEL-INST (MAKE-INSTANCE 'SSSMSELFDEVEL))

(DEFPARAMETER *SSSMHEALTHHABS-INST (MAKE-INSTANCE 'SSSMHEALTHHABS))

(DEFPARAMETER *SSCPPROBSOLV-INST (MAKE-INSTANCE 'SSCPPROBSOLV))

(DEFPARAMETER *SSCPPOSTHOUGHTS-INST (MAKE-INSTANCE 'SSCPPOSTHOUGHTS))

(DEFPARAMETER *SSCPPOSACTS-INST (MAKE-INSTANCE 'SSCPPOSACTS))

(DEFPARAMETER *SSCPNOBLAMEANGERWDRAW-INST (MAKE-INSTANCE
                                           'SSCPNOBLAMEANGERWDRAW))

(DEFPARAMETER *SSCPNOTSMOKDRUGMED-INST (MAKE-INSTANCE
                                        'SSCPNOTSMOKDRUGMED))

(DEFPARAMETER *SSCPNOTEAT-INST (MAKE-INSTANCE 'SSCPNOTEAT))

(DEFPARAMETER *HAPSDMEANSPIRITSS-INST (MAKE-INSTANCE
                                       'HAPSDMEANSPIRITSS))

(DEFPARAMETER *HAPCAREEREXSS-INST (MAKE-INSTANCE 'HAPCAREEREXSS))

(DEFPARAMETER *HAPRECPESS-INST (MAKE-INSTANCE 'HAPRECPESS))

(DEFPARAMETER *HAPAREASS-INST (MAKE-INSTANCE 'HAPAREASS))

(DEFPARAMETER *HAPFAMSS-INST (MAKE-INSTANCE 'HAPFAMSS))

(DEFPARAMETER *HAPROMSS-INST (MAKE-INSTANCE 'HAPROMSS))

(DEFPARAMETER *HAPFRIENDSSS-INST (MAKE-INSTANCE 'HAPFRIENDSSS))

(DEFPARAMETER *HAPFUTURESS-INST (MAKE-INSTANCE 'HAPFUTURESS))

(DEFPARAMETER *HAPPASTSS-INST (MAKE-INSTANCE 'HAPPASTSS))

(DEFPARAMETER *HAPRECENTSS-INST (MAKE-INSTANCE 'HAPRECENTSS))

(DEFPARAMETER *SSRECLOSEFRIENDS-INST (MAKE-INSTANCE 'SSRECLOSEFRIENDS))

(DEFPARAMETER *SSREROMRELSUC-INST (MAKE-INSTANCE 'SSREROMRELSUC))

(DEFPARAMETER *SSRENUMFRIENDS-INST (MAKE-INSTANCE 'SSRENUMFRIENDS))

(DEFPARAMETER *SSREHAPSUCFRS-INST (MAKE-INSTANCE 'SSREHAPSUCFRS))

(DEFPARAMETER *SSDELODEPSYMP-INST (MAKE-INSTANCE 'SSDELODEPSYMP))

(DEFPARAMETER *SSDELODEPTREATS-INST (MAKE-INSTANCE 'SSDELODEPTREATS))

(DEFPARAMETER *SSAXLOPERFGENANX-INST (MAKE-INSTANCE 'SSAXLOPERFGENANX))

(DEFPARAMETER *SSAXLOWFEAROCD-INST (MAKE-INSTANCE 'SSAXLOWFEAROCD))

(DEFPARAMETER *SSAXLOANXTREATS-INST (MAKE-INSTANCE 'SSAXLOANXTREATS))

(DEFPARAMETER *SSHELONEGADDICTHABS-INST (MAKE-INSTANCE
                                         'SSHELONEGADDICTHABS))

(DEFPARAMETER *SSHELOFREQILL-INST (MAKE-INSTANCE 'SSHELOFREQILL))

(DEFPARAMETER *SSHEPELOWEIGHT-INST (MAKE-INSTANCE 'SSHEPELOWEIGHT))

(DEFPARAMETER *ACAD-LEARNING-MAQS-INST (MAKE-INSTANCE
                                        'ACAD-LEARNING-MAQS))

(DEFPARAMETER *SUSERFEEDBACK-INST (MAKE-INSTANCE 'SUSERFEEDBACK))

(DEFPARAMETER *BIO-INST (MAKE-INSTANCE 'BIO))

(DEFPARAMETER *VALUES-THEMES-INST (MAKE-INSTANCE 'VALUES-THEMES))

(DEFPARAMETER *BELIEFS-INST (MAKE-INSTANCE 'BELIEFS))

(DEFPARAMETER *SKILLS-CONFIDENCE-INST (MAKE-INSTANCE
                                       'SKILLS-CONFIDENCE))

(DEFPARAMETER *INTERPERSONAL-INST (MAKE-INSTANCE 'INTERPERSONAL))

(DEFPARAMETER *ACAD-LEARNING-INST (MAKE-INSTANCE 'ACAD-LEARNING))

(DEFPARAMETER *CAREER-INTEREST-INST (MAKE-INSTANCE 'CAREER-INTEREST))

(DEFPARAMETER *OUTCOME-INST (MAKE-INSTANCE 'OUTCOME))

(DEFPARAMETER *BIO-TEXT-INST (MAKE-INSTANCE 'BIO-TEXT))

(DEFPARAMETER *INTRO-MAQ-INST (MAKE-INSTANCE 'INTRO-MAQ))

(DEFPARAMETER *BIO-MAQ-INST (MAKE-INSTANCE 'BIO-MAQ))

(DEFPARAMETER *HQ-INST (MAKE-INSTANCE 'HQ))

(DEFPARAMETER *HIGHERSELFSCALE-INST (MAKE-INSTANCE 'HIGHERSELFSCALE))

(DEFPARAMETER *SID-INST (MAKE-INSTANCE 'SID))

(DEFPARAMETER *ACAD-ACH-INST (MAKE-INSTANCE 'ACAD-ACH))

(DEFPARAMETER *NO-SCALE-INST (MAKE-INSTANCE 'NO-SCALE))

(DEFPARAMETER *SUTYPE-INST (MAKE-INSTANCE 'SUTYPE))

(DEFPARAMETER *SUGOALS-INST (MAKE-INSTANCE 'SUGOALS))

(DEFPARAMETER *ST1HIGHERSELF-INST (MAKE-INSTANCE 'ST1HIGHERSELF))

(DEFPARAMETER *ST2SOCINTIMNOFAM-INST (MAKE-INSTANCE 'ST2SOCINTIMNOFAM))

(DEFPARAMETER *ST3FAMCARE-INST (MAKE-INSTANCE 'ST3FAMCARE))

(DEFPARAMETER *ST4SUCCESSSTATUSMATER-INST (MAKE-INSTANCE
                                           'ST4SUCCESSSTATUSMATER))

(DEFPARAMETER *ST5-ORDERPERFECTIONGOODNESS-INST (MAKE-INSTANCE
                                                 'ST5-ORDERPERFECTIONGOODNESS))

(DEFPARAMETER *ST6GODSPIRITRELIG-INST (MAKE-INSTANCE
                                       'ST6GODSPIRITRELIG))

(DEFPARAMETER *ST7IMPACTCHALLENGEEXPLOR-INST (MAKE-INSTANCE
                                              'ST7IMPACTCHALLENGEEXPLOR))

(DEFPARAMETER *ST8ATTENTIONFUNEASY-INST (MAKE-INSTANCE
                                         'ST8ATTENTIONFUNEASY))

(DEFPARAMETER *ST9VALUESELFALLUNCOND-INST (MAKE-INSTANCE
                                           'ST9VALUESELFALLUNCOND))

(DEFPARAMETER *ST10OVERCMPROBACCEPTSELF-INST (MAKE-INSTANCE
                                              'ST10OVERCMPROBACCEPTSELF))

(DEFPARAMETER *ST11DUTYPUNCTUAL-INST (MAKE-INSTANCE 'ST11DUTYPUNCTUAL))

(DEFPARAMETER *SWORLDVIEW-INST (MAKE-INSTANCE 'SWORLDVIEW))

(DEFPARAMETER *STBSLFWO-INST (MAKE-INSTANCE 'STBSLFWO))

(DEFPARAMETER *SIECONTR-INST (MAKE-INSTANCE 'SIECONTR))

(DEFPARAMETER *SETHBEL-INST (MAKE-INSTANCE 'SETHBEL))

(DEFPARAMETER *SGRFEARS-INST (MAKE-INSTANCE 'SGRFEARS))

(DEFPARAMETER *SSLFCONF-INST (MAKE-INSTANCE 'SSLFCONF))

(DEFPARAMETER *SSELFMAN-INST (MAKE-INSTANCE 'SSELFMAN))

(DEFPARAMETER *SEMOTCOP-INST (MAKE-INSTANCE 'SEMOTCOP))

(DEFPARAMETER *INTSS1AASSERTCR-INST (MAKE-INSTANCE 'INTSS1AASSERTCR))

(DEFPARAMETER *INTSS1BOPENHON-INST (MAKE-INSTANCE 'INTSS1BOPENHON))

(DEFPARAMETER *INTSS2ROMANTC-INST (MAKE-INSTANCE 'INTSS2ROMANTC))

(DEFPARAMETER *INTSS3LIBROLE-INST (MAKE-INSTANCE 'INTSS3LIBROLE))

(DEFPARAMETER *INTSS4LOVERES-INST (MAKE-INSTANCE 'INTSS4LOVERES))

(DEFPARAMETER *INTSS5INDEP-INST (MAKE-INSTANCE 'INTSS5INDEP))

(DEFPARAMETER *INTSS6POSSUP-INST (MAKE-INSTANCE 'INTSS6POSSUP))

(DEFPARAMETER *INTSS7COLLAB-INST (MAKE-INSTANCE 'INTSS7COLLAB))

(DEFPARAMETER *SCOLLEGE-INST (MAKE-INSTANCE 'SCOLLEGE))

(DEFPARAMETER *SSL1CONFIDEFFICSTUDYTEST-INST (MAKE-INSTANCE
                                              'SSL1CONFIDEFFICSTUDYTEST))

(DEFPARAMETER *SSL1BCONFIDNOTAVOIDSTUDY-INST (MAKE-INSTANCE
                                              'SSL1BCONFIDNOTAVOIDSTUDY))

(DEFPARAMETER *SSL2SATISCAMPUSFACFRIENDSGRDES-INST (MAKE-INSTANCE
                                                    'SSL2SATISCAMPUSFACFRIENDSGRDES))

(DEFPARAMETER *SSL3WRITEREADSKILLS-INST (MAKE-INSTANCE
                                         'SSL3WRITEREADSKILLS))

(DEFPARAMETER *SSL4BLDMENTALSTRUCT-INST (MAKE-INSTANCE
                                         'SSL4BLDMENTALSTRUCT))

(DEFPARAMETER *SSL5BASICSTUDYSKILLS-INST (MAKE-INSTANCE
                                          'SSL5BASICSTUDYSKILLS))

(DEFPARAMETER *SSL6SELFMANACADGOALS-INST (MAKE-INSTANCE
                                          'SSL6SELFMANACADGOALS))

(DEFPARAMETER *SSL7MATHSCIPRINC-INST (MAKE-INSTANCE 'SSL7MATHSCIPRINC))

(DEFPARAMETER *SSL8STUDYENVIR-INST (MAKE-INSTANCE 'SSL8STUDYENVIR))

(DEFPARAMETER *SSL9ATTENDHW-INST (MAKE-INSTANCE 'SSL9ATTENDHW))

(DEFPARAMETER *SSL10MEMNOTANX-INST (MAKE-INSTANCE 'SSL10MEMNOTANX))

(DEFPARAMETER *SSL11NOTNONACADMOT-INST (MAKE-INSTANCE
                                        'SSL11NOTNONACADMOT))

(DEFPARAMETER *SSL12STDYTMAVAIL-INST (MAKE-INSTANCE 'SSL12STDYTMAVAIL))

(DEFPARAMETER *SSL13VERBALAPT-INST (MAKE-INSTANCE 'SSL13VERBALAPT))

(DEFPARAMETER *SSL14MATHAPT-INST (MAKE-INSTANCE 'SSL14MATHAPT))

(DEFPARAMETER *SINCAR-INST (MAKE-INSTANCE 'SINCAR))

(DEFPARAMETER *SINBUS-INST (MAKE-INSTANCE 'SINBUS))

(DEFPARAMETER *SINENGR-INST (MAKE-INSTANCE 'SINENGR))

(DEFPARAMETER *SINFINEA-INST (MAKE-INSTANCE 'SINFINEA))

(DEFPARAMETER *SINHELP-INST (MAKE-INSTANCE 'SINHELP))

(DEFPARAMETER *SINLANG-INST (MAKE-INSTANCE 'SINLANG))

(DEFPARAMETER *SINMED-INST (MAKE-INSTANCE 'SINMED))

(DEFPARAMETER *SINMILTC-INST (MAKE-INSTANCE 'SINMILTC))

(DEFPARAMETER *INNATSCI-INST (MAKE-INSTANCE 'INNATSCI))

(DEFPARAMETER *SINSOCSC-INST (MAKE-INSTANCE 'SINSOCSC))

(DEFPARAMETER *SINWOETH-INST (MAKE-INSTANCE 'SINWOETH))

(DEFPARAMETER *SINWRITE-INST (MAKE-INSTANCE 'SINWRITE))

(DEFPARAMETER *SEHAPPY-INST (MAKE-INSTANCE 'SEHAPPY))

(DEFPARAMETER *SRDEPRES-INST (MAKE-INSTANCE 'SRDEPRES))

(DEFPARAMETER *SRANXIET-INST (MAKE-INSTANCE 'SRANXIET))

(DEFPARAMETER *SRANGAGG-INST (MAKE-INSTANCE 'SRANGAGG))

(DEFPARAMETER *SRELHLTH-INST (MAKE-INSTANCE 'SRELHLTH))

(DEFPARAMETER *SRPEOPLE-INST (MAKE-INSTANCE 'SRPEOPLE))

(DEFPARAMETER *SSWVGRATPT-INST (MAKE-INSTANCE 'SSWVGRATPT))

(DEFPARAMETER *SSWVOPTIMS-INST (MAKE-INSTANCE 'SSWVOPTIMS))

(DEFPARAMETER *SSWVENTIT-INST (MAKE-INSTANCE 'SSWVENTIT))

(DEFPARAMETER *SSSWNONCONT-INST (MAKE-INSTANCE 'SSSWNONCONT))

(DEFPARAMETER *SSSWHAPALLGRAT-INST (MAKE-INSTANCE 'SSSWHAPALLGRAT))

(DEFPARAMETER *SSSWACALLSELF-INST (MAKE-INSTANCE 'SSSWACALLSELF))

(DEFPARAMETER *SSIEAUTONY-INST (MAKE-INSTANCE 'SSIEAUTONY))

(DEFPARAMETER *SSIENCODEP-INST (MAKE-INSTANCE 'SSIENCODEP))

(DEFPARAMETER *SSIENOTHER-INST (MAKE-INSTANCE 'SSIENOTHER))

(DEFPARAMETER *SSB2ETHIC-INST (MAKE-INSTANCE 'SSB2ETHIC))

(DEFPARAMETER *SSB2FORGIV-INST (MAKE-INSTANCE 'SSB2FORGIV))

(DEFPARAMETER *SSB2IDGRND-INST (MAKE-INSTANCE 'SSB2IDGRND))

(DEFPARAMETER *SSB2GRNDMNG-INST (MAKE-INSTANCE 'SSB2GRNDMNG))

(DEFPARAMETER *SSB2INRGOOD-INST (MAKE-INSTANCE 'SSB2INRGOOD))

(DEFPARAMETER *SSB2NOASTR-INST (MAKE-INSTANCE 'SSB2NOASTR))

(DEFPARAMETER *SSB2LIFAD-INST (MAKE-INSTANCE 'SSB2LIFAD))

(DEFPARAMETER *SSWFSOCIAL-INST (MAKE-INSTANCE 'SSWFSOCIAL))

(DEFPARAMETER *SSWFSELF-INST (MAKE-INSTANCE 'SSWFSELF))

(DEFPARAMETER *SSWFPOVFAI-INST (MAKE-INSTANCE 'SSWFPOVFAI))

(DEFPARAMETER *SSWFILLDEA-INST (MAKE-INSTANCE 'SSWFILLDEA))

(DEFPARAMETER *SSSCLEARN-INST (MAKE-INSTANCE 'SSSCLEARN))

(DEFPARAMETER *SSSCCOPOPT-INST (MAKE-INSTANCE 'SSSCCOPOPT))

(DEFPARAMETER *SSSCSMSMSD-INST (MAKE-INSTANCE 'SSSCSMSMSD))

(DEFPARAMETER *SSSCINTERP-INST (MAKE-INSTANCE 'SSSCINTERP))

(DEFPARAMETER *SSSCALLHELP-INST (MAKE-INSTANCE 'SSSCALLHELP))

(DEFPARAMETER *SSSCSCIENCE-INST (MAKE-INSTANCE 'SSSCSCIENCE))

(DEFPARAMETER *SSSCARTCRE-INST (MAKE-INSTANCE 'SSSCARTCRE))

(DEFPARAMETER *SSSMTIMEMANGOALSET-INST (MAKE-INSTANCE
                                        'SSSMTIMEMANGOALSET))

(DEFPARAMETER *SSSMACCOMPLORUSH-INST (MAKE-INSTANCE 'SSSMACCOMPLORUSH))

(DEFPARAMETER *SSSMSELFDEVEL-INST (MAKE-INSTANCE 'SSSMSELFDEVEL))

(DEFPARAMETER *SSSMHEALTHHABS-INST (MAKE-INSTANCE 'SSSMHEALTHHABS))

(DEFPARAMETER *SSCPPROBSOLV-INST (MAKE-INSTANCE 'SSCPPROBSOLV))

(DEFPARAMETER *SSCPPOSTHOUGHTS-INST (MAKE-INSTANCE 'SSCPPOSTHOUGHTS))

(DEFPARAMETER *SSCPPOSACTS-INST (MAKE-INSTANCE 'SSCPPOSACTS))

(DEFPARAMETER *SSCPNOBLAMEANGERWDRAW-INST (MAKE-INSTANCE
                                           'SSCPNOBLAMEANGERWDRAW))

(DEFPARAMETER *SSCPNOTSMOKDRUGMED-INST (MAKE-INSTANCE
                                        'SSCPNOTSMOKDRUGMED))

(DEFPARAMETER *SSCPNOTEAT-INST (MAKE-INSTANCE 'SSCPNOTEAT))

(DEFPARAMETER *HAPSDMEANSPIRITSS-INST (MAKE-INSTANCE
                                       'HAPSDMEANSPIRITSS))

(DEFPARAMETER *HAPCAREEREXSS-INST (MAKE-INSTANCE 'HAPCAREEREXSS))

(DEFPARAMETER *HAPRECPESS-INST (MAKE-INSTANCE 'HAPRECPESS))

(DEFPARAMETER *HAPAREASS-INST (MAKE-INSTANCE 'HAPAREASS))

(DEFPARAMETER *HAPFAMSS-INST (MAKE-INSTANCE 'HAPFAMSS))

(DEFPARAMETER *HAPROMSS-INST (MAKE-INSTANCE 'HAPROMSS))

(DEFPARAMETER *HAPFRIENDSSS-INST (MAKE-INSTANCE 'HAPFRIENDSSS))

(DEFPARAMETER *HAPFUTURESS-INST (MAKE-INSTANCE 'HAPFUTURESS))

(DEFPARAMETER *HAPPASTSS-INST (MAKE-INSTANCE 'HAPPASTSS))

(DEFPARAMETER *HAPRECENTSS-INST (MAKE-INSTANCE 'HAPRECENTSS))

(DEFPARAMETER *SSRECLOSEFRIENDS-INST (MAKE-INSTANCE 'SSRECLOSEFRIENDS))

(DEFPARAMETER *SSREROMRELSUC-INST (MAKE-INSTANCE 'SSREROMRELSUC))

(DEFPARAMETER *SSRENUMFRIENDS-INST (MAKE-INSTANCE 'SSRENUMFRIENDS))

(DEFPARAMETER *SSREHAPSUCFRS-INST (MAKE-INSTANCE 'SSREHAPSUCFRS))

(DEFPARAMETER *SSDELODEPSYMP-INST (MAKE-INSTANCE 'SSDELODEPSYMP))

(DEFPARAMETER *SSDELODEPTREATS-INST (MAKE-INSTANCE 'SSDELODEPTREATS))

(DEFPARAMETER *SSAXLOPERFGENANX-INST (MAKE-INSTANCE 'SSAXLOPERFGENANX))

(DEFPARAMETER *SSAXLOWFEAROCD-INST (MAKE-INSTANCE 'SSAXLOWFEAROCD))

(DEFPARAMETER *SSAXLOANXTREATS-INST (MAKE-INSTANCE 'SSAXLOANXTREATS))

(DEFPARAMETER *SSHELONEGADDICTHABS-INST (MAKE-INSTANCE
                                         'SSHELONEGADDICTHABS))

(DEFPARAMETER *SSHELOFREQILL-INST (MAKE-INSTANCE 'SSHELOFREQILL))

(DEFPARAMETER *SSHEPELOWEIGHT-INST (MAKE-INSTANCE 'SSHEPELOWEIGHT))

(DEFPARAMETER *ACAD-LEARNING-MAQS-INST (MAKE-INSTANCE
                                        'ACAD-LEARNING-MAQS))

(DEFPARAMETER *SUSERFEEDBACK-INST (MAKE-INSTANCE 'SUSERFEEDBACK))

(DEFPARAMETER *BIO-INST (MAKE-INSTANCE 'BIO))

(DEFPARAMETER *VALUES-THEMES-INST (MAKE-INSTANCE 'VALUES-THEMES))

(DEFPARAMETER *BELIEFS-INST (MAKE-INSTANCE 'BELIEFS))

(DEFPARAMETER *SKILLS-CONFIDENCE-INST (MAKE-INSTANCE
                                       'SKILLS-CONFIDENCE))

(DEFPARAMETER *INTERPERSONAL-INST (MAKE-INSTANCE 'INTERPERSONAL))

(DEFPARAMETER *ACAD-LEARNING-INST (MAKE-INSTANCE 'ACAD-LEARNING))

(DEFPARAMETER *CAREER-INTEREST-INST (MAKE-INSTANCE 'CAREER-INTEREST))

(DEFPARAMETER *OUTCOME-INST (MAKE-INSTANCE 'OUTCOME))

(DEFPARAMETER *BIO-TEXT-INST (MAKE-INSTANCE 'BIO-TEXT))

(DEFPARAMETER *INTRO-MAQ-INST (MAKE-INSTANCE 'INTRO-MAQ))

(DEFPARAMETER *BIO-MAQ-INST (MAKE-INSTANCE 'BIO-MAQ))

(DEFPARAMETER *HQ-INST (MAKE-INSTANCE 'HQ))

(DEFPARAMETER *HIGHERSELFSCALE-INST (MAKE-INSTANCE 'HIGHERSELFSCALE))

(DEFPARAMETER *SID-INST (MAKE-INSTANCE 'SID))

(DEFPARAMETER *ACAD-ACH-INST (MAKE-INSTANCE 'ACAD-ACH))

(DEFPARAMETER *NO-SCALE-INST (MAKE-INSTANCE 'NO-SCALE))

(DEFPARAMETER *SUTYPE-INST (MAKE-INSTANCE 'SUTYPE))

(DEFPARAMETER *SUGOALS-INST (MAKE-INSTANCE 'SUGOALS))

(DEFPARAMETER *ST1HIGHERSELF-INST (MAKE-INSTANCE 'ST1HIGHERSELF))

(DEFPARAMETER *ST2SOCINTIMNOFAM-INST (MAKE-INSTANCE 'ST2SOCINTIMNOFAM))

(DEFPARAMETER *ST3FAMCARE-INST (MAKE-INSTANCE 'ST3FAMCARE))

(DEFPARAMETER *ST4SUCCESSSTATUSMATER-INST (MAKE-INSTANCE
                                           'ST4SUCCESSSTATUSMATER))

(DEFPARAMETER *ST5-ORDERPERFECTIONGOODNESS-INST (MAKE-INSTANCE
                                                 'ST5-ORDERPERFECTIONGOODNESS))

(DEFPARAMETER *ST6GODSPIRITRELIG-INST (MAKE-INSTANCE
                                       'ST6GODSPIRITRELIG))

(DEFPARAMETER *ST7IMPACTCHALLENGEEXPLOR-INST (MAKE-INSTANCE
                                              'ST7IMPACTCHALLENGEEXPLOR))

(DEFPARAMETER *ST8ATTENTIONFUNEASY-INST (MAKE-INSTANCE
                                         'ST8ATTENTIONFUNEASY))

(DEFPARAMETER *ST9VALUESELFALLUNCOND-INST (MAKE-INSTANCE
                                           'ST9VALUESELFALLUNCOND))

(DEFPARAMETER *ST10OVERCMPROBACCEPTSELF-INST (MAKE-INSTANCE
                                              'ST10OVERCMPROBACCEPTSELF))

(DEFPARAMETER *ST11DUTYPUNCTUAL-INST (MAKE-INSTANCE 'ST11DUTYPUNCTUAL))

(DEFPARAMETER *SWORLDVIEW-INST (MAKE-INSTANCE 'SWORLDVIEW))

(DEFPARAMETER *STBSLFWO-INST (MAKE-INSTANCE 'STBSLFWO))

(DEFPARAMETER *SIECONTR-INST (MAKE-INSTANCE 'SIECONTR))

(DEFPARAMETER *SETHBEL-INST (MAKE-INSTANCE 'SETHBEL))

(DEFPARAMETER *SGRFEARS-INST (MAKE-INSTANCE 'SGRFEARS))

(DEFPARAMETER *SSLFCONF-INST (MAKE-INSTANCE 'SSLFCONF))

(DEFPARAMETER *SSELFMAN-INST (MAKE-INSTANCE 'SSELFMAN))

(DEFPARAMETER *SEMOTCOP-INST (MAKE-INSTANCE 'SEMOTCOP))

(DEFPARAMETER *INTSS1AASSERTCR-INST (MAKE-INSTANCE 'INTSS1AASSERTCR))

(DEFPARAMETER *INTSS1BOPENHON-INST (MAKE-INSTANCE 'INTSS1BOPENHON))

(DEFPARAMETER *INTSS2ROMANTC-INST (MAKE-INSTANCE 'INTSS2ROMANTC))

(DEFPARAMETER *INTSS3LIBROLE-INST (MAKE-INSTANCE 'INTSS3LIBROLE))

(DEFPARAMETER *INTSS4LOVERES-INST (MAKE-INSTANCE 'INTSS4LOVERES))

(DEFPARAMETER *INTSS5INDEP-INST (MAKE-INSTANCE 'INTSS5INDEP))

(DEFPARAMETER *INTSS6POSSUP-INST (MAKE-INSTANCE 'INTSS6POSSUP))

(DEFPARAMETER *INTSS7COLLAB-INST (MAKE-INSTANCE 'INTSS7COLLAB))

(DEFPARAMETER *SCOLLEGE-INST (MAKE-INSTANCE 'SCOLLEGE))

(DEFPARAMETER *SSL1CONFIDEFFICSTUDYTEST-INST (MAKE-INSTANCE
                                              'SSL1CONFIDEFFICSTUDYTEST))

(DEFPARAMETER *SSL1BCONFIDNOTAVOIDSTUDY-INST (MAKE-INSTANCE
                                              'SSL1BCONFIDNOTAVOIDSTUDY))

(DEFPARAMETER *SSL2SATISCAMPUSFACFRIENDSGRDES-INST (MAKE-INSTANCE
                                                    'SSL2SATISCAMPUSFACFRIENDSGRDES))

(DEFPARAMETER *SSL3WRITEREADSKILLS-INST (MAKE-INSTANCE
                                         'SSL3WRITEREADSKILLS))

(DEFPARAMETER *SSL4BLDMENTALSTRUCT-INST (MAKE-INSTANCE
                                         'SSL4BLDMENTALSTRUCT))

(DEFPARAMETER *SSL5BASICSTUDYSKILLS-INST (MAKE-INSTANCE
                                          'SSL5BASICSTUDYSKILLS))

(DEFPARAMETER *SSL6SELFMANACADGOALS-INST (MAKE-INSTANCE
                                          'SSL6SELFMANACADGOALS))

(DEFPARAMETER *SSL7MATHSCIPRINC-INST (MAKE-INSTANCE 'SSL7MATHSCIPRINC))

(DEFPARAMETER *SSL8STUDYENVIR-INST (MAKE-INSTANCE 'SSL8STUDYENVIR))

(DEFPARAMETER *SSL9ATTENDHW-INST (MAKE-INSTANCE 'SSL9ATTENDHW))

(DEFPARAMETER *SSL10MEMNOTANX-INST (MAKE-INSTANCE 'SSL10MEMNOTANX))

(DEFPARAMETER *SSL11NOTNONACADMOT-INST (MAKE-INSTANCE
                                        'SSL11NOTNONACADMOT))

(DEFPARAMETER *SSL12STDYTMAVAIL-INST (MAKE-INSTANCE 'SSL12STDYTMAVAIL))

(DEFPARAMETER *SSL13VERBALAPT-INST (MAKE-INSTANCE 'SSL13VERBALAPT))

(DEFPARAMETER *SSL14MATHAPT-INST (MAKE-INSTANCE 'SSL14MATHAPT))

(DEFPARAMETER *SINCAR-INST (MAKE-INSTANCE 'SINCAR))

(DEFPARAMETER *SINBUS-INST (MAKE-INSTANCE 'SINBUS))

(DEFPARAMETER *SINENGR-INST (MAKE-INSTANCE 'SINENGR))

(DEFPARAMETER *SINFINEA-INST (MAKE-INSTANCE 'SINFINEA))

(DEFPARAMETER *SINHELP-INST (MAKE-INSTANCE 'SINHELP))

(DEFPARAMETER *SINLANG-INST (MAKE-INSTANCE 'SINLANG))

(DEFPARAMETER *SINMED-INST (MAKE-INSTANCE 'SINMED))

(DEFPARAMETER *SINMILTC-INST (MAKE-INSTANCE 'SINMILTC))

(DEFPARAMETER *INNATSCI-INST (MAKE-INSTANCE 'INNATSCI))

(DEFPARAMETER *SINSOCSC-INST (MAKE-INSTANCE 'SINSOCSC))

(DEFPARAMETER *SINWOETH-INST (MAKE-INSTANCE 'SINWOETH))

(DEFPARAMETER *SINWRITE-INST (MAKE-INSTANCE 'SINWRITE))

(DEFPARAMETER *SEHAPPY-INST (MAKE-INSTANCE 'SEHAPPY))

(DEFPARAMETER *SRDEPRES-INST (MAKE-INSTANCE 'SRDEPRES))

(DEFPARAMETER *SRANXIET-INST (MAKE-INSTANCE 'SRANXIET))

(DEFPARAMETER *SRANGAGG-INST (MAKE-INSTANCE 'SRANGAGG))

(DEFPARAMETER *SRELHLTH-INST (MAKE-INSTANCE 'SRELHLTH))

(DEFPARAMETER *SRPEOPLE-INST (MAKE-INSTANCE 'SRPEOPLE))

(DEFPARAMETER *SSWVGRATPT-INST (MAKE-INSTANCE 'SSWVGRATPT))

(DEFPARAMETER *SSWVOPTIMS-INST (MAKE-INSTANCE 'SSWVOPTIMS))

(DEFPARAMETER *SSWVENTIT-INST (MAKE-INSTANCE 'SSWVENTIT))

(DEFPARAMETER *SSSWNONCONT-INST (MAKE-INSTANCE 'SSSWNONCONT))

(DEFPARAMETER *SSSWHAPALLGRAT-INST (MAKE-INSTANCE 'SSSWHAPALLGRAT))

(DEFPARAMETER *SSSWACALLSELF-INST (MAKE-INSTANCE 'SSSWACALLSELF))

(DEFPARAMETER *SSIEAUTONY-INST (MAKE-INSTANCE 'SSIEAUTONY))

(DEFPARAMETER *SSIENCODEP-INST (MAKE-INSTANCE 'SSIENCODEP))

(DEFPARAMETER *SSIENOTHER-INST (MAKE-INSTANCE 'SSIENOTHER))

(DEFPARAMETER *SSB2ETHIC-INST (MAKE-INSTANCE 'SSB2ETHIC))

(DEFPARAMETER *SSB2FORGIV-INST (MAKE-INSTANCE 'SSB2FORGIV))

(DEFPARAMETER *SSB2IDGRND-INST (MAKE-INSTANCE 'SSB2IDGRND))

(DEFPARAMETER *SSB2GRNDMNG-INST (MAKE-INSTANCE 'SSB2GRNDMNG))

(DEFPARAMETER *SSB2INRGOOD-INST (MAKE-INSTANCE 'SSB2INRGOOD))

(DEFPARAMETER *SSB2NOASTR-INST (MAKE-INSTANCE 'SSB2NOASTR))

(DEFPARAMETER *SSB2LIFAD-INST (MAKE-INSTANCE 'SSB2LIFAD))

(DEFPARAMETER *SSWFSOCIAL-INST (MAKE-INSTANCE 'SSWFSOCIAL))

(DEFPARAMETER *SSWFSELF-INST (MAKE-INSTANCE 'SSWFSELF))

(DEFPARAMETER *SSWFPOVFAI-INST (MAKE-INSTANCE 'SSWFPOVFAI))

(DEFPARAMETER *SSWFILLDEA-INST (MAKE-INSTANCE 'SSWFILLDEA))

(DEFPARAMETER *SSSCLEARN-INST (MAKE-INSTANCE 'SSSCLEARN))

(DEFPARAMETER *SSSCCOPOPT-INST (MAKE-INSTANCE 'SSSCCOPOPT))

(DEFPARAMETER *SSSCSMSMSD-INST (MAKE-INSTANCE 'SSSCSMSMSD))

(DEFPARAMETER *SSSCINTERP-INST (MAKE-INSTANCE 'SSSCINTERP))

(DEFPARAMETER *SSSCALLHELP-INST (MAKE-INSTANCE 'SSSCALLHELP))

(DEFPARAMETER *SSSCSCIENCE-INST (MAKE-INSTANCE 'SSSCSCIENCE))

(DEFPARAMETER *SSSCARTCRE-INST (MAKE-INSTANCE 'SSSCARTCRE))

(DEFPARAMETER *SSSMTIMEMANGOALSET-INST (MAKE-INSTANCE
                                        'SSSMTIMEMANGOALSET))

(DEFPARAMETER *SSSMACCOMPLORUSH-INST (MAKE-INSTANCE 'SSSMACCOMPLORUSH))

(DEFPARAMETER *SSSMSELFDEVEL-INST (MAKE-INSTANCE 'SSSMSELFDEVEL))

(DEFPARAMETER *SSSMHEALTHHABS-INST (MAKE-INSTANCE 'SSSMHEALTHHABS))

(DEFPARAMETER *SSCPPROBSOLV-INST (MAKE-INSTANCE 'SSCPPROBSOLV))

(DEFPARAMETER *SSCPPOSTHOUGHTS-INST (MAKE-INSTANCE 'SSCPPOSTHOUGHTS))

(DEFPARAMETER *SSCPPOSACTS-INST (MAKE-INSTANCE 'SSCPPOSACTS))

(DEFPARAMETER *SSCPNOBLAMEANGERWDRAW-INST (MAKE-INSTANCE
                                           'SSCPNOBLAMEANGERWDRAW))

(DEFPARAMETER *SSCPNOTSMOKDRUGMED-INST (MAKE-INSTANCE
                                        'SSCPNOTSMOKDRUGMED))

(DEFPARAMETER *SSCPNOTEAT-INST (MAKE-INSTANCE 'SSCPNOTEAT))

(DEFPARAMETER *HAPSDMEANSPIRITSS-INST (MAKE-INSTANCE
                                       'HAPSDMEANSPIRITSS))

(DEFPARAMETER *HAPCAREEREXSS-INST (MAKE-INSTANCE 'HAPCAREEREXSS))

(DEFPARAMETER *HAPRECPESS-INST (MAKE-INSTANCE 'HAPRECPESS))

(DEFPARAMETER *HAPAREASS-INST (MAKE-INSTANCE 'HAPAREASS))

(DEFPARAMETER *HAPFAMSS-INST (MAKE-INSTANCE 'HAPFAMSS))

(DEFPARAMETER *HAPROMSS-INST (MAKE-INSTANCE 'HAPROMSS))

(DEFPARAMETER *HAPFRIENDSSS-INST (MAKE-INSTANCE 'HAPFRIENDSSS))

(DEFPARAMETER *HAPFUTURESS-INST (MAKE-INSTANCE 'HAPFUTURESS))

(DEFPARAMETER *HAPPASTSS-INST (MAKE-INSTANCE 'HAPPASTSS))

(DEFPARAMETER *HAPRECENTSS-INST (MAKE-INSTANCE 'HAPRECENTSS))

(DEFPARAMETER *SSRECLOSEFRIENDS-INST (MAKE-INSTANCE 'SSRECLOSEFRIENDS))

(DEFPARAMETER *SSREROMRELSUC-INST (MAKE-INSTANCE 'SSREROMRELSUC))

(DEFPARAMETER *SSRENUMFRIENDS-INST (MAKE-INSTANCE 'SSRENUMFRIENDS))

(DEFPARAMETER *SSREHAPSUCFRS-INST (MAKE-INSTANCE 'SSREHAPSUCFRS))

(DEFPARAMETER *SSDELODEPSYMP-INST (MAKE-INSTANCE 'SSDELODEPSYMP))

(DEFPARAMETER *SSDELODEPTREATS-INST (MAKE-INSTANCE 'SSDELODEPTREATS))

(DEFPARAMETER *SSAXLOPERFGENANX-INST (MAKE-INSTANCE 'SSAXLOPERFGENANX))

(DEFPARAMETER *SSAXLOWFEAROCD-INST (MAKE-INSTANCE 'SSAXLOWFEAROCD))

(DEFPARAMETER *SSAXLOANXTREATS-INST (MAKE-INSTANCE 'SSAXLOANXTREATS))

(DEFPARAMETER *SSHELONEGADDICTHABS-INST (MAKE-INSTANCE
                                         'SSHELONEGADDICTHABS))

(DEFPARAMETER *SSHELOFREQILL-INST (MAKE-INSTANCE 'SSHELOFREQILL))

(DEFPARAMETER *SSHEPELOWEIGHT-INST (MAKE-INSTANCE 'SSHEPELOWEIGHT))

(DEFPARAMETER *ACAD-LEARNING-MAQS-INST (MAKE-INSTANCE
                                        'ACAD-LEARNING-MAQS))

(DEFPARAMETER *SUSERFEEDBACK-INST (MAKE-INSTANCE 'SUSERFEEDBACK))
