;; ********************* test-code.lisp **********************
;; PROBLEM OF TRYING TO EVAL :MULTI-SEL-QUEST AS :SINGLE-SEL
;;
(STMAJGPA "st-Major GPA" :SINGLE "3.5-4.0 (A)" "1.000" 8 5 8 8 SCORED-NORMAL GPA8ANSARRAY) (STACADST "st-AcadStatus" :SINGLE "President's List--over 3.5 GPA last semester" "1.000" 6 6 6 6 SCORED-NORMAL STUACADEMICSTATUS) :MULTI-SEL-QUEST #24="stucolle" (STUCOLLE :MULTI #24# "st-College attending" 7 ("cocsulb" "1" 1 T 1 7 NIL) ("cccsu" "2" 1 NIL 0 7 NIL) ("coucal" "3" 1 NIL 0 7 NIL) ("coopublc" "4" 1 T 1 7 NIL) ("coprivca" "5" 1 NIL 0 7 NIL) ("coprivot" "6" 1 T 1 7 NIL) ("cocacomc" "7" 1 NIL 0 7 NIL) ("coothcc" "8" 1 NIL 0 7 NIL) ("coothnat" "9" 1 NIL 0 7 NIL) ("coprgrad" "10" 1 NIL 0 7 NIL) ("cotech" "11" 1 NIL 0 7 NIL) ("highsch" "12" 1 NIL 0 7 NIL) ("coother" "13" 1 NIL 0 7 NIL)) :MULTI-SEL-QUEST #25="stumajor" (STUMAJOR :MULTI #25# "st-Major study area" 8 ("mlibart" "1" 1 NIL 0 8 NIL) ("msocsci" "2" 1 NIL 0 8 NIL) ("mbiolsci" "3" 1 NIL 0 8 NIL) ("mart" "4" 1 NIL 0 8 NIL) ("mnatsci" "5" 1 NIL 0 8 NIL) ("mbus" "6" 1 NIL 0 8 NIL) ("menginr" "7" 1 NIL 0 8 NIL) ("meducat" "8" 1 NIL 0 8 NIL) ("mmedical" "9" 1 NIL 0 8 NIL) ("motcompu" "10" 1 NIL 0 8 NIL) ("mothtech" "11" 1 NIL 0 8 NIL) ("mrecrpe" "12" 1 NIL 0 8 NIL) ("mdoesna" "13" 1 NIL 0 8 NIL) ("mundecid" "14" 1 NIL 0 8 NIL)) :MULTI-SEL-QUEST #26="stuspeci" (STUSPECI :MULTI #26# "st-Special status" 9 ("strancc" "1" 1 NIL 0 9 NIL) ("stran4yr" "2" 1 NIL 0 9 NIL) ("sadultre" "3" 1 NIL 0 9 NIL) ("seop" "4" 1 NIL 0 9 NIL) ("susimmig" "5" 1 NIL 0 9 NIL) ("svisa" "6" 1 NIL 0 9 NIL) ("shonor" "7" 1 NIL 0 9 NIL) ("svisastu" "8" 1 NIL 0 9 NIL) ("sdisabld" "9" 1 NIL 0 9 NIL) ("soutofst" "10" 1 NIL 0 9 NIL) ("smilitar" "11" 1 NIL 0 9 NIL) ("sathlete" "12" 1 NIL 0 9 NIL) ("snone" "13" 1 NIL 0 9 NIL)) 



(setf *test-links
'((("h3hiself.htm" "Ch3 Higher Self" "Ch-3 Develop Your Higher Self: The part that loves you unconditionally" "http://www.csulb.edu/~tstevens/h3hiself.htm") 1.176) (("h87focus.htm" "MC6 Focus " "Mental Control Strategy 6: Focus" "http://www.csulb.edu/~tstevens/h87focus.htm") ("h86optim.htm" "MC5 Optimism" "Mental Control Strategy 5: Optimism" "http://www.csulb.edu/~tstevens/h86optim.htm") 1.086)  (("h9patsm.htm" "Ch9 Self-Management" "Ch-9: Create a Better World for Yourself and Others: Get control of your time and yourself " "http://www.csulb.edu/~tstevens/h9patsm.htm") ("possi.htm" "Overwhelming Projects" "Managing and Completing Overwhelming and Complex Tasks and Projects Using POSSI" "http://www.csulb.edu/~tstevens/possi.htm") ("h23explo.htm" "Self-Exploration" "Use Self-Exploration to find your inner sources of unhappiness" "http://www.csulb.edu/~tstevens/h23explo.htm") 1.0120001) (("h9patsm.htm" "Ch9 Self-Management" "Ch-9: Create a Better World for Yourself and Others: Get control of your time and yourself " "http://www.csulb.edu/~tstevens/h9patsm.htm") 0.99) (("h9patsm.htm" "Ch9 Self-Management" "Ch-9: Create a Better World for Yourself and Others: Get control of your time and yourself " "http://www.csulb.edu/~tstevens/h9patsm.htm") 0.926) (("h51worth.htm" "Unconditional Self-Worth" "What is unconditional self-worth and how do I get it?" "http://www.csulb.edu/~tstevens/h51worth.htm") 0.908)  (("conversational_skills.htm" "Meeting, Dating Skills" "Skills For Meeting People, Dating, and 
Developing Intimacy" "http://www.csulb.edu/~tstevens/conversational_skills.htm") ("developing_intimacy.htm" "Relationship Harmony" "Harmonious Relationships: Achieving Intimacy and Assertiveness" "http://www.csulb.edu/~tstevens/developing_intimacy.htm") 1.0780001) (("health tips.htm" "Health Habits" "You Can Choose To Be Healthy by Changing Health Habits" "http://www.csulb.edu/~tstevens/health tips.htm") ("weight_control.htm" "Weight Control" "Help Getting Control of Your Weight" "http://www.csulb.edu/~tstevens/weight_control.htm") ("substance_abuse.htm" "Substance Abuse" "Substance Abuse" "http://www.csulb.edu/~tstevens/substance_abuse.htm") 0.88399995) (("conversational_skills.htm" "Meeting, Dating Skills" "Skills For Meeting People, Dating, and 
Developing Intimacy" "http://www.csulb.edu/~tstevens/conversational_skills.htm") ("assertion_training.htm" "Assertion Training" "Assertion Training" "http://www.csulb.edu/~tstevens/assertion_training.htm") ("overcoming_loneliness.htm" "Lonely?" "Methods of coping with loneliness, fears of rejection, and shyness" "http://www.csulb.edu/~tstevens/overcoming_loneliness.htm") 0.9359999)))

(my-sort-lists 0 *test-links :from-end T )

(my-greaterp 1.086 1.176)

(my-list-nth-greaterp 0  
'(("h87focus.htm" "MC6 Focus " "Mental Control Strategy 6: Focus" "http://www.csulb.edu/~tstevens/h87focus.htm") ("h86optim.htm" "MC5 Optimism" "Mental Control Strategy 5: Optimism" "http://www.csulb.edu/~tstevens/h86optim.htm") 1.086)

'(("h3hiself.htm" "Ch3 Higher Self" "Ch-3 Develop Your Higher Self: The part that loves you unconditionally" "http://www.csulb.edu/~tstevens/h3hiself.htm") 1.176)
  :from-end T) = works
((("h3hiself.htm" "Ch3 Higher Self" "Ch-3 Develop Your Higher Self: The part that loves you unconditionally" "http://www.csulb.edu/~tstevens/h3hiself.htm") 1.176) (("h87focus.htm" "MC6 Focus " "Mental Control Strategy 6: Focus" "http://www.csulb.edu/~tstevens/h87focus.htm") ("h86optim.htm" "MC5 Optimism" "Mental Control Strategy 5: Optimism" "http://www.csulb.edu/~tstevens/h86optim.htm") 1.086))
NIL

(delete-duplicates '("this" "THAT" "WHAT" "THIS" "that") :test 'string-equal :from-end t)